POST /api/2.3/auctions/2fad508852384ef7b62fdb69b2239597/awards/27de40b4b1f34704bd129d137793f41c/documents?acc_token=2b3771d637ee4a69bc526df9419d9346 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 386
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/989fc783c3dc44a8a10a2d6db93ec6e3?KeyID=65db22b2&Signature=6AR2DH2oHchcNpplCmByuYizLrQSH0TGK61nnK1t0oyFkeyba8%2Fgxe9ZDf0GD2QIYVaxcynpA%2Fyx%2Br0mHg0kAw%3D%3D", 
    "title": "Disqualified_reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2fad508852384ef7b62fdb69b2239597/awards/27de40b4b1f34704bd129d137793f41c/documents/c4e5cb5569f1482fbe00d0ce67a45d53

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/989fc783c3dc44a8a10a2d6db93ec6e3?KeyID=65db22b2&Signature=g3uPJmhgGvac%252Bwj3VQuz18dNCBp6SJNzNQyhs6IaOyaNX5eDvu%2FLYp8ftimUUxysmPeTIRXpE2aeqVmVvguDDw%253D%253D", 
    "title": "Disqualified_reason.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-02T19:52:44.260574+02:00", 
    "dateModified": "2016-12-02T19:52:44.260628+02:00", 
    "id": "c4e5cb5569f1482fbe00d0ce67a45d53"
  }
}

