POST /api/2.3/auctions/259c7703ce68422e8c436195e56505bf/awards/7d925e654ad942bd865f4bac5c6e34d1/documents?acc_token=90b60080a3a045f2b487d17fbbccf77a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 382
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/67a0367308ce4269b22fa529bd772b79?KeyID=4a8daaf3&Signature=fl6vi6S9a5XBXhBXpljZdlUPpYcQoG01LzhyfOMWeIzySemTOo%2FibA62MLZYHJRh3AL3hsgu7ADOkl1tKe90DQ%3D%3D", 
    "title": "Disqualified_reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/259c7703ce68422e8c436195e56505bf/awards/7d925e654ad942bd865f4bac5c6e34d1/documents/a98b4c463580499bb1a47c92f918485c

{
  "data": {
    "dateModified": "2018-03-13T14:17:00.666701+02:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "author": "auction_owner", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/67a0367308ce4269b22fa529bd772b79?KeyID=4a8daaf3&Signature=8uduzwaCrRZAEQLjv9b3qK3M9PjBGb%2FKnbQR8bXUueGXAQGFHV50QRRPNAuhjXS6%2F1eJ6JA5EqxFaCH6VQ4GBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-03-13T14:17:00.666680+02:00", 
    "title": "Disqualified_reason.pdf", 
    "id": "a98b4c463580499bb1a47c92f918485c"
  }
}

