GET /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pdf", 
          "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a61c0c8cf98f41589dc659bb83e34fa1?KeyID=3d7a7dcd&Signature=KHCp2PHImBpmOyv%2F907qdf1GeVLMLxoQlzgh5VOZKp7MhLrZktRgshgI4806eEuFgIog%2FcQgA%2FOQwpEpfjKIDg%253D%253D", 
          "title": "Unsuccessful_Reason.pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-09-13T14:12:27.705053+03:00", 
          "dateModified": "2016-09-13T14:12:27.705080+03:00", 
          "id": "b3e1bab5d5ed464b99996f676483c57a"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-09-13T14:12:27.508742+03:00", 
        "endDate": "2016-09-13T14:12:33.479095+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "9fc37e06b2be405d80ad66633e125557", 
      "value": {
        "currency": "UAH", 
        "amount": 479.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-13T14:12:33.494743+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "tendererActionDate": "2016-09-13T14:12:29.920436+03:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "id": "6b2e541b811b4dff89a77f154522fcf4", 
          "dateAnswered": "2016-09-13T14:12:29.920405+03:00", 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateSubmitted": "2016-09-13T14:12:29.354756+03:00", 
          "complaintID": "UA-EA-2016-09-13-000001.5", 
          "date": "2016-09-13T14:12:30.159773+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "documents": [
            {
              "dateModified": "2016-09-13T14:12:29.127832+03:00", 
              "hash": "md5:00000000000000000000000000000000", 
              "format": "application/pdf", 
              "url": "http://public.docs-sandbox.ea.openprocurement.org/get/84d6346df8444253a3a8ad3d71cb904a?KeyID=3d7a7dcd&Signature=LMrQGmzKEn59n7PX6Vw6M6tfRjqS2CzrTqMi7d20i2Ma%2Fg7jAtS%252BTqz824Xbf1omelWo9LOKV7JFchNWAYRjDQ%253D%253D", 
              "author": "complaint_owner", 
              "documentOf": "tender", 
              "datePublished": "2016-09-13T14:12:29.127806+03:00", 
              "title": "Complaint_Attachement.pdf", 
              "id": "46a6661a92814b93b8b75c1396ca8627"
            }
          ]
        }, 
        {
          "status": "invalid", 
          "dateDecision": "2016-09-13T14:12:30.836752+03:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-09-13T14:12:30.607898+03:00", 
          "dateAnswered": "2016-09-13T14:12:30.385701+03:00", 
          "dateSubmitted": "2016-09-13T14:12:29.559423+03:00", 
          "complaintID": "UA-EA-2016-09-13-000001.6", 
          "date": "2016-09-13T14:12:30.847871+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "b6cf1038ca464f49bb2bc12ec56c5c8e"
        }, 
        {
          "status": "resolved", 
          "dateDecision": "2016-09-13T14:12:32.801903+03:00", 
          "documents": [
            {
              "dateModified": "2016-09-13T14:12:32.531384+03:00", 
              "hash": "md5:00000000000000000000000000000000", 
              "format": "application/pdf", 
              "url": "http://public.docs-sandbox.ea.openprocurement.org/get/fec176fc0782488195f13adb856b3d8a?KeyID=3d7a7dcd&Signature=q%252B9POsA%2FPuEL%252BnJYxopI8RCWoLcnCMmx6h3jbHnzFgGOZ4iRwK2buPuNwPXXwt2%2FkCeicVUdMnDl%2Fv6GiPquAg%253D%253D", 
              "author": "reviewers", 
              "documentOf": "tender", 
              "datePublished": "2016-09-13T14:12:32.531353+03:00", 
              "title": "ComplaintResolution.pdf", 
              "id": "e9e55f740cac4bb3baa5ed6e51dc50a6"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-09-13T14:12:31.545857+03:00", 
          "dateAnswered": "2016-09-13T14:12:31.307104+03:00", 
          "dateSubmitted": "2016-09-13T14:12:31.060347+03:00", 
          "complaintID": "UA-EA-2016-09-13-000001.7", 
          "date": "2016-09-13T14:12:32.814643+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "bd8870b6bb504875893322c0a042b158"
        }, 
        {
          "status": "declined", 
          "dateDecision": "2016-09-13T14:12:33.059539+03:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-09-13T14:12:32.278620+03:00", 
          "dateAnswered": "2016-09-13T14:12:32.022547+03:00", 
          "dateSubmitted": "2016-09-13T14:12:31.780591+03:00", 
          "complaintID": "UA-EA-2016-09-13-000001.8", 
          "date": "2016-09-13T14:12:33.075552+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "eb35dd784cd74d7ba8eba611a5c3f1b6"
        }
      ], 
      "id": "2c1639d846c74bff94ae0e140ff97b3c"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-09-13T14:12:27.855834+03:00", 
        "endDate": "2016-09-13T14:12:33.479095+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "25f079c40e4348d6b78e4348b9b342c9", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-13T14:12:28.316068+03:00", 
      "id": "07ab5caf7d80499da257f2db4a5fe70c"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pdf", 
          "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8a5933cdb29d4dd4ab9a3e8c11020317?KeyID=3d7a7dcd&Signature=ykbXt0YRdA03p9xbzMwM2%252BJKbWHrSVMfyXbV%252BZowjre6oYX7jSZ3mxr0%252BkCWBjUQvRmX8DSSiEXb9AtyGL%2FRBQ%253D%253D", 
          "title": "Cancellation_Reason.pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-09-13T14:12:28.549527+03:00", 
          "dateModified": "2016-09-13T14:12:28.549554+03:00", 
          "id": "77929654512c4a588c2ad4da79db3514"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-09-13T14:12:28.302840+03:00", 
        "endDate": "2016-09-13T14:12:33.479095+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "25f079c40e4348d6b78e4348b9b342c9", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-13T14:12:33.494743+03:00", 
      "id": "5b1449a5db484206b1da0564010aec02"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-09-13T14:12:28.739954+03:00", 
        "endDate": "2016-09-13T14:12:33.479095+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "e90e908d88e04616b712a288b972e643", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-13T14:12:33.494743+03:00", 
      "id": "0703a829a5ff4bd287ad56612f6e2e6c"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-09-13T14:12:33.479829+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "9fc37e06b2be405d80ad66633e125557", 
      "value": {
        "currency": "UAH", 
        "amount": 479.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-13T14:12:33.479814+03:00", 
      "id": "63fe05f6aae14179a16e8377c52a1a3a"
    }
  ]
}

