GET /api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pdf", 
          "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a264fb59171a43ae909081830ae8063c?KeyID=3a39b727&Signature=YDSNL6qFGZWG6jLpnjTIFJirqKfdSFZhgweWhOhOnEf%252BL4nDiHZc6lZaOLJv0eF5sSS9zMH%2Fv45r0aTe0PIOCg%253D%253D", 
          "title": "Unsuccessful_Reason.pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-09-16T14:45:59.135035+03:00", 
          "dateModified": "2016-09-16T14:45:59.135065+03:00", 
          "id": "a010dd89028c458bba72f97535340fab"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-09-16T14:45:58.927011+03:00", 
        "endDate": "2016-09-16T14:46:05.582213+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "f83585defafa4d5587584462c777f11d", 
      "value": {
        "currency": "UAH", 
        "amount": 479.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-16T14:46:05.599536+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "tendererActionDate": "2016-09-16T14:46:01.672361+03:00", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": true, 
          "id": "457abc613a2147978675f09766dd3a00", 
          "dateAnswered": "2016-09-16T14:46:01.672338+03:00", 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateSubmitted": "2016-09-16T14:46:01.032829+03:00", 
          "complaintID": "UA-EA-2016-09-16-000001.5", 
          "date": "2016-09-16T14:46:01.946318+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "documents": [
            {
              "dateModified": "2016-09-16T14:46:00.795558+03:00", 
              "hash": "md5:00000000000000000000000000000000", 
              "format": "application/pdf", 
              "url": "http://public.docs-sandbox.ea.openprocurement.org/get/49d08ceb3b414ba981c16579a5953d79?KeyID=3a39b727&Signature=HHApb6KzY5V6EAghveeT5Ovy1S2GW4mXKWYJMJiiCac2whxbT%252B9kl%2Fc8Dqzweipcem%252BSHIkblCX5m%2FMK%2FY%252BsCg%253D%253D", 
              "author": "complaint_owner", 
              "documentOf": "tender", 
              "datePublished": "2016-09-16T14:46:00.795516+03:00", 
              "title": "Complaint_Attachement.pdf", 
              "id": "359d6544490f4303a39175b5b52d97ab"
            }
          ]
        }, 
        {
          "status": "invalid", 
          "dateDecision": "2016-09-16T14:46:02.668315+03:00", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateEscalated": "2016-09-16T14:46:02.420860+03:00", 
          "dateAnswered": "2016-09-16T14:46:02.174543+03:00", 
          "dateSubmitted": "2016-09-16T14:46:01.277428+03:00", 
          "complaintID": "UA-EA-2016-09-16-000001.6", 
          "date": "2016-09-16T14:46:02.680508+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "2a5e5495c81c40baa62a124022109798"
        }, 
        {
          "status": "resolved", 
          "dateDecision": "2016-09-16T14:46:04.844489+03:00", 
          "documents": [
            {
              "dateModified": "2016-09-16T14:46:04.530077+03:00", 
              "hash": "md5:00000000000000000000000000000000", 
              "format": "application/pdf", 
              "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5983d39d45f74d0aaa9e14207bfef5cc?KeyID=3a39b727&Signature=T5kSSRZGQ7irzXziZbVse5MxPRMQGHwpTLOMrVe41HfQv0NLnM3u36HFv1A%252BNIUIkaPP9Cjk2v2ejEfprxQ2Cw%253D%253D", 
              "author": "reviewers", 
              "documentOf": "tender", 
              "datePublished": "2016-09-16T14:46:04.530047+03:00", 
              "title": "ComplaintResolution.pdf", 
              "id": "2e6cc945eef44642b28899ad369a649e"
            }
          ], 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateEscalated": "2016-09-16T14:46:03.460098+03:00", 
          "dateAnswered": "2016-09-16T14:46:03.189506+03:00", 
          "dateSubmitted": "2016-09-16T14:46:02.936664+03:00", 
          "complaintID": "UA-EA-2016-09-16-000001.7", 
          "date": "2016-09-16T14:46:04.859272+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "6f4b49b3c01247f5af682fc1e0bd2ed3"
        }, 
        {
          "status": "declined", 
          "dateDecision": "2016-09-16T14:46:05.130635+03:00", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateEscalated": "2016-09-16T14:46:04.264099+03:00", 
          "dateAnswered": "2016-09-16T14:46:03.995694+03:00", 
          "dateSubmitted": "2016-09-16T14:46:03.718449+03:00", 
          "complaintID": "UA-EA-2016-09-16-000001.8", 
          "date": "2016-09-16T14:46:05.144395+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "cd09f2d38096463aa1adbdedd121b872"
        }
      ], 
      "id": "349e0f1f79d04aa488ec9e296e6e441e"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-09-16T14:45:59.305755+03:00", 
        "endDate": "2016-09-16T14:46:05.582213+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "3b18501cfdab4a528ba4169eef524bd9", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-16T14:45:59.812293+03:00", 
      "id": "3ca390da62db4fc7929972a6a44b50c6"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pdf", 
          "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e189e7bc29e64fb0968f29f232705da6?KeyID=3a39b727&Signature=%252BQoxpt4gzNdTqKtKJ3a5qPWa%2FrlX6mUD%252B0p%252BHHZHlHHAVvnjjMpYWk5iVtx%2FZEErJ2j%2FFz%2FC68aaMT9qlm6DAw%253D%253D", 
          "title": "Cancellation_Reason.pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-09-16T14:46:00.059853+03:00", 
          "dateModified": "2016-09-16T14:46:00.059883+03:00", 
          "id": "3e87e25eb8f1490bb0bbea6313db103e"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-09-16T14:45:59.797135+03:00", 
        "endDate": "2016-09-16T14:46:05.582213+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "3b18501cfdab4a528ba4169eef524bd9", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-16T14:46:05.599536+03:00", 
      "id": "4eff8334dfc543ccbd36e94645128ce5"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-09-16T14:46:00.268453+03:00", 
        "endDate": "2016-09-16T14:46:05.582213+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "b4af3993e3b64317a76b5707fa495aaf", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-16T14:46:05.599536+03:00", 
      "id": "d207dd0b95ee4399b36842efd7e54b9a"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-09-16T14:46:05.583037+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "f83585defafa4d5587584462c777f11d", 
      "value": {
        "currency": "UAH", 
        "amount": 479.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-16T14:46:05.583019+03:00", 
      "id": "fe74f96b44a8492ca92a7ff64d4d0e05"
    }
  ]
}

