PATCH /api/2.3/auctions/ed8ca274ce4e4fa5866ee44ef7532b1a/awards/48362ddbfe824ffa8a2120c973dba606?acc_token=6bfaf230f39946a189db2c4059cd06d0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "dateModified": "2017-02-01T13:22:16.343232+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/2d9c39c4461e46248f9a664396b69492?KeyID=bdf7219a&Signature=GoVcuaS%252BgNcVjKprg0I%252BKmDYFoMfIzim%2F7fNlZ%252BmFkduQtB6PrqRTlbYbOm66zZE5pDSOOjlOhc3VMC5%252Br7mBw%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-02-01T13:22:16.343205+02:00", 
        "documentType": "auctionProtocol", 
        "title": "auction_protocol.pdf", 
        "id": "9713fd6de895463780be80a9ae3f431f"
      }, 
      {
        "dateModified": "2017-02-01T13:22:16.483255+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Disqualification reason", 
        "author": "auction_owner", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/21c823c5a0ec4697bd6a5cc3b0122d32?KeyID=bdf7219a&Signature=LLkfr6Wttje6APz8XmHc2fdF42p2me6VnudCe%252Bgmf68TAhdhbTO2re3Ynqg9H9nOr9Y7UGSXMZ3htHSg3kdnDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-01T13:22:16.483227+02:00", 
        "title": "Disqualified_reason.pdf", 
        "id": "c79442dc5cd647038d3f533365252eee"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2017-02-01T13:22:16.205551+02:00", 
      "endDate": "2017-02-01T13:22:16.618487+02:00"
    }, 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified", 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2017-02-01T13:22:15.773890+02:00", 
      "endDate": "2017-02-01T13:22:16.618487+02:00"
    }, 
    "bid_id": "000e593d3fee415dacd0f41d4a94a4b9", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-01T13:22:16.630113+02:00", 
    "id": "48362ddbfe824ffa8a2120c973dba606"
  }
}

