POST /api/2.3/auctions/2ab1c0e4ba204b30bba372eecaaace11/awards/dd8cd96a69c049b9ab4acbdcc94275af/documents?acc_token=476c2c602dfb4d67ac0aaab357d98ec9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 386
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/70f6296c01ba4acca5fcf0d8522f8049?KeyID=cbd09987&Signature=YcnoA4oLcEPx4QsVvvL7BDwl7eEwv%2B7g5%2Fg%2BUadmc7fxZ580XntWZmigfod7VMBjpkOsm9ZjlXV59T1AxFAsDg%3D%3D", 
    "title": "Disqualified_reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2ab1c0e4ba204b30bba372eecaaace11/awards/dd8cd96a69c049b9ab4acbdcc94275af/documents/481b3ed11b9c482bb89660a0584b2572

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "author": "auction_owner", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/70f6296c01ba4acca5fcf0d8522f8049?KeyID=cbd09987&Signature=o%252BzE%2F%252BYp7Jw2%2FTkZ567011iOCuj0sKAp2cUND08E7DDSC%252BwluACMyjJe%252B3KYrDyx7AVGBFU33u%252BxTpsYkFUmBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-13T15:47:14.873585+02:00", 
    "id": "481b3ed11b9c482bb89660a0584b2572", 
    "title": "Disqualified_reason.pdf", 
    "dateModified": "2017-02-13T15:47:14.873612+02:00"
  }
}

