PATCH /api/2.3/auctions/2d8e78cabae043838db7d364b71533a2/awards/8908ec55d8da4c5a872a304bf7fa5a39?acc_token=3525886d14aa4539a905a9866eba0af8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2d8e78cabae043838db7d364b71533a2/awards/a0d0ead108df49058e3789d5b3e59b94

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2016-12-02T18:39:06.454080+02:00", 
      "endDate": "2016-12-02T18:39:06.639199+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "3758c27ffcc647bfa0becb45134cae8c", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-12-02T18:39:06.825528+02:00", 
    "id": "8908ec55d8da4c5a872a304bf7fa5a39"
  }
}

