GET /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-09-13T14:12:27.508742+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "9fc37e06b2be405d80ad66633e125557", 
      "value": {
        "currency": "UAH", 
        "amount": 479.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-13T14:12:27.508727+03:00", 
      "id": "2c1639d846c74bff94ae0e140ff97b3c"
    }
  ]
}

