PATCH /api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/awards/2e41f6b9e16b47d18184af47c1ce37e3?acc_token=9f96d4481ec74a0d8d1982609d8c6e4b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/awards/807f7d09e0514af58a9f233cda33e534

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3696994cf5c24f6b87ad87a0ae830e9b?KeyID=757edc4c&Signature=L8A1pNFwmyi7ocZephrWZp6c0p%2FUEMDq%252B%252BjGC8Fin%252BD13f6rl3kfQN6XWj55Lo0oq%2Fsn6Qff34smBqeY8WNLAg%253D%253D", 
        "title": "Unsuccessful_Reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-09T19:51:44.293747+03:00", 
        "dateModified": "2016-09-09T19:51:44.293780+03:00", 
        "id": "75693f4acc87456f9f356a452db1e852"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-09-09T19:51:44.048822+03:00", 
      "endDate": "2016-09-13T19:51:44.484619+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "2afafaa7e9ec4fd6906b899a9df5109a", 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-09-09T19:51:44.497219+03:00", 
    "id": "2e41f6b9e16b47d18184af47c1ce37e3"
  }
}

