PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/bd0bd4d123b544659dbb97f1e317709e?acc_token=49cf29bf5bf5451688daf03617f22a6c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/84b771f261b14ca786822cb53a7d2dc0

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/353edf6a4e354fcfafc0a06296533622?KeyID=d1402da7&Signature=KYYIMm5Xjq%252Bc7HkMet%2FBjZRTqCADWv6yF8Z9Qalsugzq112LJZd8fGMy9SkDtn6USIFn7cYZ7jTnpVU6C1IgBA%253D%253D", 
        "title": "Unsuccessful_Reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:38.788529+03:00", 
        "dateModified": "2016-09-14T15:36:38.788558+03:00", 
        "id": "ee091eb13c3944deb4914a02078aa95b"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-09-14T15:36:38.564317+03:00", 
      "endDate": "2016-09-14T15:36:46.037080+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "7aa283f5d6944825ba355c0ef900d087", 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-09-14T15:36:46.056930+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "tendererActionDate": "2016-09-14T15:36:41.598373+03:00", 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": true, 
        "id": "72ed6a40ef8c431c98b0c13aa860f032", 
        "dateAnswered": "2016-09-14T15:36:41.598345+03:00", 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateSubmitted": "2016-09-14T15:36:40.946297+03:00", 
        "complaintID": "UA-EA-2016-09-14-000001.5", 
        "date": "2016-09-14T15:36:41.895616+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "documents": [
          {
            "dateModified": "2016-09-14T15:36:40.672347+03:00", 
            "hash": "md5:00000000000000000000000000000000", 
            "format": "application/pdf", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c48a1c3cb8434c569ebaa592ef2287d9?KeyID=d1402da7&Signature=4pzORGsvIemMqXRu0l9WFleTU%2FOaGS5oOvT%2FlUgvF%252Bq7lZCjlPVxUeuk%2FoFc4hAzaJqEJ2iVPT9geJhGQ52zCw%253D%253D", 
            "author": "complaint_owner", 
            "documentOf": "tender", 
            "datePublished": "2016-09-14T15:36:40.672317+03:00", 
            "title": "Complaint_Attachement.pdf", 
            "id": "a08e1b2f307d4079ab876cf0c994d257"
          }
        ]
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2016-09-14T15:36:42.731281+03:00", 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "complaint", 
        "title": "complaint title", 
        "satisfied": false, 
        "dateEscalated": "2016-09-14T15:36:42.455195+03:00", 
        "dateAnswered": "2016-09-14T15:36:42.157381+03:00", 
        "dateSubmitted": "2016-09-14T15:36:41.184063+03:00", 
        "complaintID": "UA-EA-2016-09-14-000001.6", 
        "date": "2016-09-14T15:36:42.745012+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "736e80e2357d40e8ac9ff068d4c0acfb"
      }, 
      {
        "status": "resolved", 
        "dateDecision": "2016-09-14T15:36:45.095384+03:00", 
        "documents": [
          {
            "dateModified": "2016-09-14T15:36:44.733631+03:00", 
            "hash": "md5:00000000000000000000000000000000", 
            "format": "application/pdf", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3c7aa98cc6e741d0b72e6f55db8725a8?KeyID=d1402da7&Signature=I2k9UDIoIbCE6QGxsLD9iAMx0bEP%252BTCKvwenkyY4dnOuvSDk%2F3MivxxbnFHUGwuAt%252BX4cc6n%2FDt%252B7u%252BGLYwKCA%253D%253D", 
            "author": "reviewers", 
            "documentOf": "tender", 
            "datePublished": "2016-09-14T15:36:44.733600+03:00", 
            "title": "ComplaintResolution.pdf", 
            "id": "10b4428063a648f2aa4943eca553bc8e"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "complaint", 
        "title": "complaint title", 
        "satisfied": false, 
        "dateEscalated": "2016-09-14T15:36:43.596111+03:00", 
        "dateAnswered": "2016-09-14T15:36:43.290656+03:00", 
        "dateSubmitted": "2016-09-14T15:36:43.020801+03:00", 
        "complaintID": "UA-EA-2016-09-14-000001.7", 
        "date": "2016-09-14T15:36:45.114728+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "fbfa9ecfd4c145dd812c044c87e6e7fd"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2016-09-14T15:36:45.462264+03:00", 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "complaint", 
        "title": "complaint title", 
        "satisfied": false, 
        "dateEscalated": "2016-09-14T15:36:44.449028+03:00", 
        "dateAnswered": "2016-09-14T15:36:44.157999+03:00", 
        "dateSubmitted": "2016-09-14T15:36:43.870451+03:00", 
        "complaintID": "UA-EA-2016-09-14-000001.8", 
        "date": "2016-09-14T15:36:45.480330+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "7af6dba808dc43b7ac6ba73f16fdd72e"
      }
    ], 
    "id": "bd0bd4d123b544659dbb97f1e317709e"
  }
}

