PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/1f3e8a170b0342f38a7e174b658ae836?acc_token=49cf29bf5bf5451688daf03617f22a6c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/f42a56e16b5545da8bb107a3cdfc17e4

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/22cbcc507265480c85f83580ff39a1a0?KeyID=d1402da7&Signature=rJsn9MO9%2FiWjI%2F%252BG69OtWqXc7Cpso%2Fb6HlBhWPp48D7DyJhaWl0r%2F56nCmI76%252Bfd6SN6%2F7k3RChg12dNOh85Bg%253D%253D", 
        "title": "Cancellation_Reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:39.955562+03:00", 
        "dateModified": "2016-09-14T15:36:39.955591+03:00", 
        "id": "5cd662a104d343559e6ab5e9967ed8a5"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-09-14T15:36:39.658869+03:00", 
      "endDate": "2016-09-16T15:36:40.187231+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "b185c6363bee4e80af35e62963969356", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-09-14T15:36:40.201106+03:00", 
    "id": "1f3e8a170b0342f38a7e174b658ae836"
  }
}

