PATCH /api/2.3/auctions/6428763175bc491b9514dc7de4771281/awards/0be2b9c4dc4b43a8a203b239d726a74f?acc_token=fa248967de2244439451050d2499166d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/6428763175bc491b9514dc7de4771281/awards/153fcdbbcfd64ab38b2279cc474787f8

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ceec00f1e1fe45d4823b6cff73a5e6e2?KeyID=278be238&Signature=GSt%2FNNdHL%252BgkEhjgxHCBjmWNNVMei%2FQA%252BZ65LBLXAxaZbYdfeLDwfvaGA0Wi%2FwCkAczFZKDsUkK0m5NItNxtDQ%253D%253D", 
        "title": "Unsuccessful_Reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T16:17:46.934420+03:00", 
        "dateModified": "2016-09-16T16:17:46.934449+03:00", 
        "id": "b52b77a5e21b4f7cafd0c9f44ca7932f"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-09-16T16:17:46.702347+03:00", 
      "endDate": "2016-09-20T16:17:47.101766+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "5e687c10e6964f3087d491a63b692a02", 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-09-16T16:17:47.113324+03:00", 
    "id": "0be2b9c4dc4b43a8a203b239d726a74f"
  }
}

