PATCH /api/2.3/auctions/f6a8d0f1fd564397b3f1fd30ce85b004/awards/d87ec5270edc4b879678bf002353e8a0?acc_token=86aae1a55f6b45779e49ca7dc8a100c1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2017-02-15T11:48:46.210702+02:00", 
      "endDate": "2017-02-15T11:48:46.435268+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "228b7e67141b464eb6fac7258ff00757", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-15T11:48:46.445215+02:00", 
    "id": "d87ec5270edc4b879678bf002353e8a0"
  }
}

