GET /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-09-14T15:36:38.564317+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "7aa283f5d6944825ba355c0ef900d087", 
      "value": {
        "currency": "UAH", 
        "amount": 479.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-09-14T15:36:38.564295+03:00", 
      "id": "bd0bd4d123b544659dbb97f1e317709e"
    }
  ]
}

