PATCH /api/2.3/auctions/259c7703ce68422e8c436195e56505bf/awards/7d925e654ad942bd865f4bac5c6e34d1?acc_token=90b60080a3a045f2b487d17fbbccf77a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "unsuccessful", 
    "paymentPeriod": {
      "startDate": "2018-03-13T14:17:00.465960+02:00"
    }, 
    "documents": [
      {
        "dateModified": "2018-03-13T14:17:00.574662+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/27e90f8b3a4a44548f39c9f566a24c6f?KeyID=4a8daaf3&Signature=rQY4T5kNmZAb4sUTXeBO%252BORoWHwlrqNbV7%2FSlGprf8VdusX4zTcBDBFuWcQvGzLbiwut7lhCSQ2ZfxFZiu3lCQ%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T14:17:00.574642+02:00", 
        "documentType": "auctionProtocol", 
        "title": "auction_protocol.pdf", 
        "id": "034c7a0a36aa453d8e12bf2d352b73f7"
      }, 
      {
        "dateModified": "2018-03-13T14:17:00.666701+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Disqualification reason", 
        "author": "auction_owner", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/67a0367308ce4269b22fa529bd772b79?KeyID=4a8daaf3&Signature=8uduzwaCrRZAEQLjv9b3qK3M9PjBGb%2FKnbQR8bXUueGXAQGFHV50QRRPNAuhjXS6%2F1eJ6JA5EqxFaCH6VQ4GBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T14:17:00.666680+02:00", 
        "title": "Disqualified_reason.pdf", 
        "id": "a98b4c463580499bb1a47c92f918485c"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-03-13T14:17:00.465960+02:00", 
      "endDate": "2018-03-13T14:17:00.769362+02:00"
    }, 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified", 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-03-13T14:17:00.204168+02:00", 
      "endDate": "2018-03-13T14:17:00.769362+02:00"
    }, 
    "bid_id": "a4f299a1dcd54224bb9821e58e8d6675", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-03-13T14:17:00.780676+02:00", 
    "id": "7d925e654ad942bd865f4bac5c6e34d1", 
    "signingPeriod": {
      "startDate": "2018-03-13T14:17:00.465960+02:00", 
      "endDate": "2018-03-13T14:37:08.924293+02:00"
    }
  }
}

