PATCH /api/2.3/auctions/e909e370deb242cbb607a456b3955c2b/awards/4291330acac74b8a9a76b03f7d894d83?acc_token=f46dae821f364cc6bb7d9d5cf7a6352f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/e909e370deb242cbb607a456b3955c2b/awards/fbf44a0f5b864725af36248ea4925aff

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2016-09-20T14:49:22.537040+03:00", 
      "endDate": "2016-09-20T14:49:22.671119+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "f2700dcc5e9146f29c8f028dfd4ddf0f", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-09-20T14:49:22.793791+03:00", 
    "id": "4291330acac74b8a9a76b03f7d894d83"
  }
}

