PATCH /api/2.3/auctions/6428763175bc491b9514dc7de4771281/awards/0be2b9c4dc4b43a8a203b239d726a74f?acc_token=fa248967de2244439451050d2499166d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/6428763175bc491b9514dc7de4771281/awards/f61c70311cfd453687654723e3a333b6

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ceec00f1e1fe45d4823b6cff73a5e6e2?KeyID=278be238&Signature=GSt%2FNNdHL%252BgkEhjgxHCBjmWNNVMei%2FQA%252BZ65LBLXAxaZbYdfeLDwfvaGA0Wi%2FwCkAczFZKDsUkK0m5NItNxtDQ%253D%253D", 
        "title": "Unsuccessful_Reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T16:17:46.934420+03:00", 
        "dateModified": "2016-09-16T16:17:46.934449+03:00", 
        "id": "b52b77a5e21b4f7cafd0c9f44ca7932f"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-09-16T16:17:46.702347+03:00", 
      "endDate": "2016-09-16T16:17:53.699559+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "5e687c10e6964f3087d491a63b692a02", 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-09-16T16:17:53.717039+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "tendererActionDate": "2016-09-16T16:17:49.565691+03:00", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": true, 
        "id": "cf9360b712ac479ea06d6c606c9db8d1", 
        "dateAnswered": "2016-09-16T16:17:49.565661+03:00", 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateSubmitted": "2016-09-16T16:17:48.899601+03:00", 
        "complaintID": "UA-EA-2016-09-16-000001.5", 
        "date": "2016-09-16T16:17:49.849593+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "documents": [
          {
            "dateModified": "2016-09-16T16:17:48.648245+03:00", 
            "hash": "md5:00000000000000000000000000000000", 
            "format": "application/pdf", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e9e1c7c580e747439db62314cee0c630?KeyID=278be238&Signature=PkGIj3rCf9L6lh1r0ErzGghZY4ghfWLkaRr6c5iTN6sUi%252BF2OYjnZ3VVTIgJ5oxhNtL0EwQmTu0eLbATexD1CQ%253D%253D", 
            "author": "complaint_owner", 
            "documentOf": "tender", 
            "datePublished": "2016-09-16T16:17:48.648216+03:00", 
            "title": "Complaint_Attachement.pdf", 
            "id": "1f8fc9d2042f420b92b7aaa4cba24a43"
          }
        ]
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2016-09-16T16:17:50.645131+03:00", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "complaint", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateEscalated": "2016-09-16T16:17:50.369724+03:00", 
        "dateAnswered": "2016-09-16T16:17:50.099347+03:00", 
        "dateSubmitted": "2016-09-16T16:17:49.137058+03:00", 
        "complaintID": "UA-EA-2016-09-16-000001.6", 
        "date": "2016-09-16T16:17:50.659654+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "5a6fc5709c4b4eb7a1adf84c9a8a2cce"
      }, 
      {
        "status": "resolved", 
        "dateDecision": "2016-09-16T16:17:52.929570+03:00", 
        "documents": [
          {
            "dateModified": "2016-09-16T16:17:52.615704+03:00", 
            "hash": "md5:00000000000000000000000000000000", 
            "format": "application/pdf", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/10b2098547f941858fa63609dfefe02d?KeyID=278be238&Signature=e3moEZBo6gWiPI9UAheRHa1w%2FLkWmIs1mj%2FmiMip%252BKzgLNyzIGNpShGzJ9NJOfFzh1SDbsUBIXhFoOomCGB6Dw%253D%253D", 
            "author": "reviewers", 
            "documentOf": "tender", 
            "datePublished": "2016-09-16T16:17:52.615675+03:00", 
            "title": "ComplaintResolution.pdf", 
            "id": "ee0fbfdd6e2e4f24b7483cbc8383b520"
          }
        ], 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "complaint", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateEscalated": "2016-09-16T16:17:51.456780+03:00", 
        "dateAnswered": "2016-09-16T16:17:51.175990+03:00", 
        "dateSubmitted": "2016-09-16T16:17:50.911841+03:00", 
        "complaintID": "UA-EA-2016-09-16-000001.7", 
        "date": "2016-09-16T16:17:52.943580+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "fe684319f9dd417fa680a252363f67aa"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2016-09-16T16:17:53.230797+03:00", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "complaint", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateEscalated": "2016-09-16T16:17:52.345519+03:00", 
        "dateAnswered": "2016-09-16T16:17:52.060798+03:00", 
        "dateSubmitted": "2016-09-16T16:17:51.765641+03:00", 
        "complaintID": "UA-EA-2016-09-16-000001.8", 
        "date": "2016-09-16T16:17:53.245306+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "b7534a5af3b74f028355f2de973fd25b"
      }
    ], 
    "id": "0be2b9c4dc4b43a8a203b239d726a74f"
  }
}

