PATCH /api/2.3/auctions/2fad508852384ef7b62fdb69b2239597/awards/27de40b4b1f34704bd129d137793f41c?acc_token=2b3771d637ee4a69bc526df9419d9346 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2fad508852384ef7b62fdb69b2239597/awards/29fa621c25c9474f97218727d825fae4

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Disqualification reason", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/989fc783c3dc44a8a10a2d6db93ec6e3?KeyID=65db22b2&Signature=g3uPJmhgGvac%252Bwj3VQuz18dNCBp6SJNzNQyhs6IaOyaNX5eDvu%2FLYp8ftimUUxysmPeTIRXpE2aeqVmVvguDDw%253D%253D", 
        "title": "Disqualified_reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-02T19:52:44.260574+02:00", 
        "dateModified": "2016-12-02T19:52:44.260628+02:00", 
        "id": "c4e5cb5569f1482fbe00d0ce67a45d53"
      }
    ], 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "complaintPeriod": {
      "startDate": "2016-12-02T19:52:44.025803+02:00", 
      "endDate": "2016-12-02T19:52:44.475165+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "title": "Disqualified", 
    "bid_id": "3c10053a459b48759e0f8bd371133786", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-12-02T19:52:44.498472+02:00", 
    "id": "27de40b4b1f34704bd129d137793f41c"
  }
}

