PATCH /api/2.3/auctions/2077a4e50e744ab6bc3936e6a0bb77a0/awards/1f629b26ea7342b5922dbe25fa5d73d6?acc_token=fcd6d3da53ec4cddae13d6cbc2dddb3c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2016-11-25T12:16:20.198316+02:00", 
      "endDate": "2016-11-25T12:16:20.390329+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "d1c66a2ce84d4feaab56c312b13ead4d", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-11-25T12:16:20.399036+02:00", 
    "id": "1f629b26ea7342b5922dbe25fa5d73d6"
  }
}

