PATCH /api/2.3/auctions/527c93f82b7b4627a9e6ed442d7ddb87/awards/a1e8aa4e26c84559a42ae6fb50b2e016?acc_token=2133855fd49140dfa76c092ca6c0d05d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/527c93f82b7b4627a9e6ed442d7ddb87/awards/b6564b43f2074397b38adbe5742c25e9

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2016-11-29T12:46:28.818643+02:00", 
      "endDate": "2016-11-29T12:46:28.966597+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "84b75d5df0da4269802f6fa7ee51d89a", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-11-29T12:46:29.099479+02:00", 
    "id": "a1e8aa4e26c84559a42ae6fb50b2e016"
  }
}

