POST /api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/awards/2e41f6b9e16b47d18184af47c1ce37e3/complaints/82d665ed408f45958d8aded09cec6bc3/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 346
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/139a636f34464e97933d04d5e78f20ba?KeyID=757edc4c&Signature=905Bg52387U6aYJ17eyGi144yJlZdi8xRDjEa0%2F4Uf%2FTGIED%2FihNju4WdOCuXmKPYvUaCWan4Vvfu4u5Xcg%2FBQ%3D%3D", 
    "title": "ComplaintResolution.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/awards/2e41f6b9e16b47d18184af47c1ce37e3/complaints/82d665ed408f45958d8aded09cec6bc3/documents/fc1f78b280414d7fa9a9cafb61cf7ed5

{
  "data": {
    "dateModified": "2016-09-09T19:51:49.952406+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/139a636f34464e97933d04d5e78f20ba?KeyID=757edc4c&Signature=udcZxGt1BZefDeL8IP4tZQCXrcWXLo3dTVojGfYustnV4Xm1AT2xftHqNFCjngKFs5AeoXJjawdPsWpE954XCw%253D%253D", 
    "author": "reviewers", 
    "documentOf": "tender", 
    "datePublished": "2016-09-09T19:51:49.952377+03:00", 
    "title": "ComplaintResolution.pdf", 
    "id": "fc1f78b280414d7fa9a9cafb61cf7ed5"
  }
}

