PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/bd0bd4d123b544659dbb97f1e317709e/complaints/736e80e2357d40e8ac9ff068d4c0acfb?acc_token=eb208d91db0b49ea8bff9c8d51bfe71a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-14T15:36:42.455195+03:00", 
    "dateAnswered": "2016-09-14T15:36:42.157381+03:00", 
    "dateSubmitted": "2016-09-14T15:36:41.184063+03:00", 
    "complaintID": "UA-EA-2016-09-14-000001.6", 
    "date": "2016-09-14T15:36:42.469134+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "736e80e2357d40e8ac9ff068d4c0acfb"
  }
}

