POST /api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/awards/2e41f6b9e16b47d18184af47c1ce37e3/complaints/5c6dd05ffe354dfdafd6dd01064d9203/documents?acc_token=12d1264598284233aeacf740a530d6ec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 350
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1e6e1c194cbc4f6d994bca40b5130bc4?KeyID=757edc4c&Signature=euu8WP%2Fl59zTfNdrmDNtWIZfcRs0nQAsn82Jmlx1D%2FinBBIxJDbj9GDurARE8Y%2FwFhPQ2Qykv%2FUv%2BH6SdIZECQ%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/awards/2e41f6b9e16b47d18184af47c1ce37e3/complaints/5c6dd05ffe354dfdafd6dd01064d9203/documents/d1e9a31eba534cc188ccdf1093babb43

{
  "data": {
    "dateModified": "2016-09-09T19:51:45.958452+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1e6e1c194cbc4f6d994bca40b5130bc4?KeyID=757edc4c&Signature=kRaJVsAitN4M26bc%252B2xTpHTqcRXHcpnzomyBOmcitG3cDxb0DcQDn2ktN5z9kBoeIUSFw5mcV%2FfS%2FgkvLrVNDg%253D%253D", 
    "author": "complaint_owner", 
    "documentOf": "tender", 
    "datePublished": "2016-09-09T19:51:45.958422+03:00", 
    "title": "Complaint_Attachement.pdf", 
    "id": "d1e9a31eba534cc188ccdf1093babb43"
  }
}

