PATCH /api/2.3/auctions/6428763175bc491b9514dc7de4771281/awards/0be2b9c4dc4b43a8a203b239d726a74f/complaints/5a6fc5709c4b4eb7a1adf84c9a8a2cce HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "invalid"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "invalid", 
    "dateDecision": "2016-09-16T16:17:50.645131+03:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-16T16:17:50.369724+03:00", 
    "dateAnswered": "2016-09-16T16:17:50.099347+03:00", 
    "dateSubmitted": "2016-09-16T16:17:49.137058+03:00", 
    "complaintID": "UA-EA-2016-09-16-000001.6", 
    "date": "2016-09-16T16:17:50.659654+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "5a6fc5709c4b4eb7a1adf84c9a8a2cce"
  }
}

