PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/bd0bd4d123b544659dbb97f1e317709e/complaints/7af6dba808dc43b7ac6ba73f16fdd72e HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-09-14T15:36:45.462264+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-09-14T15:36:44.449028+03:00", 
    "dateAnswered": "2016-09-14T15:36:44.157999+03:00", 
    "dateSubmitted": "2016-09-14T15:36:43.870451+03:00", 
    "complaintID": "UA-EA-2016-09-14-000001.8", 
    "date": "2016-09-14T15:36:45.480330+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "7af6dba808dc43b7ac6ba73f16fdd72e"
  }
}

