PATCH /api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/awards/349e0f1f79d04aa488ec9e296e6e441e/complaints/6f4b49b3c01247f5af682fc1e0bd2ed3 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-09-16T14:46:04.844489+03:00", 
    "documents": [
      {
        "dateModified": "2016-09-16T14:46:04.530077+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5983d39d45f74d0aaa9e14207bfef5cc?KeyID=3a39b727&Signature=T5kSSRZGQ7irzXziZbVse5MxPRMQGHwpTLOMrVe41HfQv0NLnM3u36HFv1A%252BNIUIkaPP9Cjk2v2ejEfprxQ2Cw%253D%253D", 
        "author": "reviewers", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T14:46:04.530047+03:00", 
        "title": "ComplaintResolution.pdf", 
        "id": "2e6cc945eef44642b28899ad369a649e"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-16T14:46:03.460098+03:00", 
    "dateAnswered": "2016-09-16T14:46:03.189506+03:00", 
    "dateSubmitted": "2016-09-16T14:46:02.936664+03:00", 
    "complaintID": "UA-EA-2016-09-16-000001.7", 
    "date": "2016-09-16T14:46:04.859272+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "6f4b49b3c01247f5af682fc1e0bd2ed3"
  }
}

