PATCH /api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/awards/349e0f1f79d04aa488ec9e296e6e441e/complaints/457abc613a2147978675f09766dd3a00?acc_token=86772ef18d854c42bc50040fcedaddb4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "dateModified": "2016-09-16T14:46:00.795558+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/49d08ceb3b414ba981c16579a5953d79?KeyID=3a39b727&Signature=HHApb6KzY5V6EAghveeT5Ovy1S2GW4mXKWYJMJiiCac2whxbT%252B9kl%2Fc8Dqzweipcem%252BSHIkblCX5m%2FMK%2FY%252BsCg%253D%253D", 
        "author": "complaint_owner", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T14:46:00.795516+03:00", 
        "title": "Complaint_Attachement.pdf", 
        "id": "359d6544490f4303a39175b5b52d97ab"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "complaint title", 
    "dateSubmitted": "2016-09-16T14:46:01.032829+03:00", 
    "complaintID": "UA-EA-2016-09-16-000001.5", 
    "date": "2016-09-16T14:46:01.044362+03:00", 
    "type": "claim", 
    "id": "457abc613a2147978675f09766dd3a00"
  }
}

