PATCH /api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/awards/349e0f1f79d04aa488ec9e296e6e441e/complaints/2a5e5495c81c40baa62a124022109798 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "invalid"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "invalid", 
    "dateDecision": "2016-09-16T14:46:02.668315+03:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-16T14:46:02.420860+03:00", 
    "dateAnswered": "2016-09-16T14:46:02.174543+03:00", 
    "dateSubmitted": "2016-09-16T14:46:01.277428+03:00", 
    "complaintID": "UA-EA-2016-09-16-000001.6", 
    "date": "2016-09-16T14:46:02.680508+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "2a5e5495c81c40baa62a124022109798"
  }
}

