POST /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/awards/2c1639d846c74bff94ae0e140ff97b3c/complaints/bd8870b6bb504875893322c0a042b158/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 348
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/fec176fc0782488195f13adb856b3d8a?KeyID=3d7a7dcd&Signature=UmWMlbb4Orsz%2FAU2Gvxh5squZWPhb%2Fz5Iu2dDE5NjI%2BBhg96kCQL6mS27Bxt%2BrIqfQS8aAH%2BgvJgomvWZlDYBg%3D%3D", 
    "title": "ComplaintResolution.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/awards/2c1639d846c74bff94ae0e140ff97b3c/complaints/bd8870b6bb504875893322c0a042b158/documents/e9e55f740cac4bb3baa5ed6e51dc50a6

{
  "data": {
    "dateModified": "2016-09-13T14:12:32.531384+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/fec176fc0782488195f13adb856b3d8a?KeyID=3d7a7dcd&Signature=q%252B9POsA%2FPuEL%252BnJYxopI8RCWoLcnCMmx6h3jbHnzFgGOZ4iRwK2buPuNwPXXwt2%2FkCeicVUdMnDl%2Fv6GiPquAg%253D%253D", 
    "author": "reviewers", 
    "documentOf": "tender", 
    "datePublished": "2016-09-13T14:12:32.531353+03:00", 
    "title": "ComplaintResolution.pdf", 
    "id": "e9e55f740cac4bb3baa5ed6e51dc50a6"
  }
}

