PATCH /api/2.3/auctions/6428763175bc491b9514dc7de4771281/awards/0be2b9c4dc4b43a8a203b239d726a74f/complaints/b7534a5af3b74f028355f2de973fd25b HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-09-16T16:17:53.230797+03:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-16T16:17:52.345519+03:00", 
    "dateAnswered": "2016-09-16T16:17:52.060798+03:00", 
    "dateSubmitted": "2016-09-16T16:17:51.765641+03:00", 
    "complaintID": "UA-EA-2016-09-16-000001.8", 
    "date": "2016-09-16T16:17:53.245306+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "b7534a5af3b74f028355f2de973fd25b"
  }
}

