PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/awards/bd0bd4d123b544659dbb97f1e317709e/complaints/72ed6a40ef8c431c98b0c13aa860f032?acc_token=55583fe6411d43e9bbaf16b24fe2e104 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "tendererActionDate": "2016-09-14T15:36:41.598373+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": true, 
    "id": "72ed6a40ef8c431c98b0c13aa860f032", 
    "dateAnswered": "2016-09-14T15:36:41.598345+03:00", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateSubmitted": "2016-09-14T15:36:40.946297+03:00", 
    "complaintID": "UA-EA-2016-09-14-000001.5", 
    "date": "2016-09-14T15:36:41.895616+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "documents": [
      {
        "dateModified": "2016-09-14T15:36:40.672347+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c48a1c3cb8434c569ebaa592ef2287d9?KeyID=d1402da7&Signature=4pzORGsvIemMqXRu0l9WFleTU%2FOaGS5oOvT%2FlUgvF%252Bq7lZCjlPVxUeuk%2FoFc4hAzaJqEJ2iVPT9geJhGQ52zCw%253D%253D", 
        "author": "complaint_owner", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:40.672317+03:00", 
        "title": "Complaint_Attachement.pdf", 
        "id": "a08e1b2f307d4079ab876cf0c994d257"
      }
    ]
  }
}

