PATCH /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/awards/2c1639d846c74bff94ae0e140ff97b3c/complaints/6b2e541b811b4dff89a77f154522fcf4?acc_token=363332e3f7c142ddafea98dfc7cd5eb6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "tendererActionDate": "2016-09-13T14:12:29.920436+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "id": "6b2e541b811b4dff89a77f154522fcf4", 
    "dateAnswered": "2016-09-13T14:12:29.920405+03:00", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateSubmitted": "2016-09-13T14:12:29.354756+03:00", 
    "complaintID": "UA-EA-2016-09-13-000001.5", 
    "date": "2016-09-13T14:12:29.931638+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "documents": [
      {
        "dateModified": "2016-09-13T14:12:29.127832+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/84d6346df8444253a3a8ad3d71cb904a?KeyID=3d7a7dcd&Signature=LMrQGmzKEn59n7PX6Vw6M6tfRjqS2CzrTqMi7d20i2Ma%2Fg7jAtS%252BTqz824Xbf1omelWo9LOKV7JFchNWAYRjDQ%253D%253D", 
        "author": "complaint_owner", 
        "documentOf": "tender", 
        "datePublished": "2016-09-13T14:12:29.127806+03:00", 
        "title": "Complaint_Attachement.pdf", 
        "id": "46a6661a92814b93b8b75c1396ca8627"
      }
    ]
  }
}

