PATCH /api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/complaints/09acae019edd45c9924e8618231ec6d9?acc_token=7f486eee90914b7db341b9285f7f3c98 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "tendererActionDate": "2016-09-16T14:45:56.508024+03:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "id": "09acae019edd45c9924e8618231ec6d9", 
    "dateAnswered": "2016-09-16T14:45:56.508001+03:00", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateSubmitted": "2016-09-16T14:45:56.289475+03:00", 
    "complaintID": "UA-EA-2016-09-16-000001.1", 
    "date": "2016-09-16T14:45:56.512773+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "documents": [
      {
        "dateModified": "2016-09-16T14:45:56.192122+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d8518ab42495440abb24b1f2c3a40995?KeyID=3a39b727&Signature=J7oVUnaW%2FCe7lP9eUPtTQRKt7rD3xyKDv%252B%252B7Lm7oYnaOKtY%252B5%2FnSfDp1tlVBSYmvLyK5YmHi1GA3cnkLF0%2F1BA%253D%253D", 
        "author": "complaint_owner", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T14:45:56.192083+03:00", 
        "title": "Complaint_Attachement.pdf", 
        "id": "589160327ae2416ea75d1a0edc21220e"
      }
    ]
  }
}

