PATCH /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/complaints/dc3aac65873a45df87a59d33a50ade9b?acc_token=ff4825e4b05849638e305b1de48d4bb1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "tendererActionDate": "2016-09-13T14:12:25.275853+03:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "id": "dc3aac65873a45df87a59d33a50ade9b", 
    "dateAnswered": "2016-09-13T14:12:25.275827+03:00", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateSubmitted": "2016-09-13T14:12:25.067440+03:00", 
    "complaintID": "UA-EA-2016-09-13-000001.1", 
    "date": "2016-09-13T14:12:25.369795+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "documents": [
      {
        "dateModified": "2016-09-13T14:12:24.987697+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/01d2bbf8bfe14578a9278a9a79d4c286?KeyID=3d7a7dcd&Signature=0TnbJVZrSQtnqGy6FT45sBCiE7mVGNuoyTBIrd2HKJ6gesYDQKkLdNE6C0VXrgPy0fzr1GkdiUJmmwokZsMPBg%253D%253D", 
        "author": "complaint_owner", 
        "documentOf": "tender", 
        "datePublished": "2016-09-13T14:12:24.987670+03:00", 
        "title": "Complaint_Attachement.pdf", 
        "id": "f4bee228b6064a218fe1222e3635f1cc"
      }
    ]
  }
}

