PATCH /api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/complaints/4a4ca82922c1499789156a474302a399?acc_token=bc9c72e3e3bc47509baf885ac64580b8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-09T19:51:41.720421+03:00", 
    "dateAnswered": "2016-09-09T19:51:41.626156+03:00", 
    "dateSubmitted": "2016-09-09T19:51:41.201149+03:00", 
    "complaintID": "UA-EA-2016-09-09-000001.2", 
    "date": "2016-09-09T19:51:41.725533+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "4a4ca82922c1499789156a474302a399"
  }
}

