PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/complaints/51f23fcd5f5d4617b055a6d246f11956 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "invalid"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "invalid", 
    "dateDecision": "2016-09-14T15:36:36.532049+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-09-14T15:36:36.436113+03:00", 
    "dateAnswered": "2016-09-14T15:36:36.344001+03:00", 
    "dateSubmitted": "2016-09-14T15:36:36.010322+03:00", 
    "complaintID": "UA-EA-2016-09-14-000001.2", 
    "date": "2016-09-14T15:36:36.536791+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "51f23fcd5f5d4617b055a6d246f11956"
  }
}

