PATCH /api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/complaints/66b9b4c48cb140b3a4b584e8c9c060f1 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-09-09T19:51:42.859934+03:00", 
    "documents": [
      {
        "dateModified": "2016-09-09T19:51:42.710377+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/eee64d1cea164b3f8f359621d1c2b160?KeyID=757edc4c&Signature=Wfv1plXGAXiaWjT20ogIelhJD1dr1FeYd4YE2I0b6yhVuGMMezUEwCXWHqBF5rzxw%2FF1raYvuN3yJdEzYgfZCg%253D%253D", 
        "author": "reviewers", 
        "documentOf": "tender", 
        "datePublished": "2016-09-09T19:51:42.710338+03:00", 
        "title": "ComplaintResolution.pdf", 
        "id": "e3ecee004b374e7888c2135e8191701f"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-09-09T19:51:42.128561+03:00", 
    "dateAnswered": "2016-09-09T19:51:42.022019+03:00", 
    "dateSubmitted": "2016-09-09T19:51:41.913339+03:00", 
    "complaintID": "UA-EA-2016-09-09-000001.3", 
    "date": "2016-09-09T19:51:42.867005+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "66b9b4c48cb140b3a4b584e8c9c060f1"
  }
}

