POST /api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/complaints/66b9b4c48cb140b3a4b584e8c9c060f1/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 342
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/eee64d1cea164b3f8f359621d1c2b160?KeyID=757edc4c&Signature=SvnmV3GmMrhyvvlA8%2F8CJoWWcc1k91NJUftcJ188IeAL7QHDgBgKAAr4fCxI5IlZav13vF4TCjs5SuBF5V%2FEAg%3D%3D", 
    "title": "ComplaintResolution.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0636cdb4cca4476e8d0b13be031c63e0/complaints/66b9b4c48cb140b3a4b584e8c9c060f1/documents/e3ecee004b374e7888c2135e8191701f

{
  "data": {
    "dateModified": "2016-09-09T19:51:42.710377+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/eee64d1cea164b3f8f359621d1c2b160?KeyID=757edc4c&Signature=Wfv1plXGAXiaWjT20ogIelhJD1dr1FeYd4YE2I0b6yhVuGMMezUEwCXWHqBF5rzxw%2FF1raYvuN3yJdEzYgfZCg%253D%253D", 
    "author": "reviewers", 
    "documentOf": "tender", 
    "datePublished": "2016-09-09T19:51:42.710338+03:00", 
    "title": "ComplaintResolution.pdf", 
    "id": "e3ecee004b374e7888c2135e8191701f"
  }
}

