PATCH /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/complaints/65d412fa4af64c91b30704ba776415d0 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-09-13T14:12:26.564283+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-09-13T14:12:26.212485+03:00", 
    "dateAnswered": "2016-09-13T14:12:26.106133+03:00", 
    "dateSubmitted": "2016-09-13T14:12:26.002135+03:00", 
    "complaintID": "UA-EA-2016-09-13-000001.4", 
    "date": "2016-09-13T14:12:26.569666+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "65d412fa4af64c91b30704ba776415d0"
  }
}

