PATCH /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/complaints/7ef5abf1a0444d3095a8bcb47e42f325?acc_token=d649b835aa0544d4be7b6d875e3c45b2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-09-13T14:12:25.531507+03:00", 
    "dateAnswered": "2016-09-13T14:12:25.446965+03:00", 
    "dateSubmitted": "2016-09-13T14:12:25.137123+03:00", 
    "complaintID": "UA-EA-2016-09-13-000001.2", 
    "date": "2016-09-13T14:12:25.536098+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "7ef5abf1a0444d3095a8bcb47e42f325"
  }
}

