PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/complaints/bc50f4f6eff544d2b960990ae22ad2e5 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-09-14T15:36:37.408607+03:00", 
    "documents": [
      {
        "dateModified": "2016-09-14T15:36:37.278331+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/816c963f7c494f409b3e1896541ce761?KeyID=d1402da7&Signature=mgmVsx0FXfm55zkCtPXz0yHXbx5UquZ%252BI7tWydZzGq3U%2F730mVNj4Sm5QDqfgQTDQ0WF6eIx%252BN%252Bm1IWY4QPyCQ%253D%253D", 
        "author": "reviewers", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:37.278301+03:00", 
        "title": "ComplaintResolution.pdf", 
        "id": "52caf249998f4645b397dd237eb153a1"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-09-14T15:36:36.829982+03:00", 
    "dateAnswered": "2016-09-14T15:36:36.722483+03:00", 
    "dateSubmitted": "2016-09-14T15:36:36.621591+03:00", 
    "complaintID": "UA-EA-2016-09-14-000001.3", 
    "date": "2016-09-14T15:36:37.414760+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "bc50f4f6eff544d2b960990ae22ad2e5"
  }
}

