POST /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/complaints/7fe8ada700024e5e98c9ccab8456861c/documents?acc_token=8c643bae8b6a4a9eb9b464f931361d5c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 346
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/23048ec4566b4488a2741ea4287ccafe?KeyID=d1402da7&Signature=g5w0s9J%2Bl3n%2Bf%2BXytc7t1wtbiYE4vwvMH4C7OrUrm0yAkbUamSjbKoItTNXhSnwnsdx0pEcSAZEjEA1zj1LGBw%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/complaints/7fe8ada700024e5e98c9ccab8456861c/documents/17d413e8396349a789e40006c408a4e0

{
  "data": {
    "dateModified": "2016-09-14T15:36:35.844251+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/23048ec4566b4488a2741ea4287ccafe?KeyID=d1402da7&Signature=PGyzRPP4oSlIDyYSPoYnJE5pPw1yZ0nDnCBiG4w6M1tcPq1ey1Zyn05HV%2FVqBfl%252BpVzKLzcvUVaCFoGmRMitDA%253D%253D", 
    "author": "complaint_owner", 
    "documentOf": "tender", 
    "datePublished": "2016-09-14T15:36:35.844221+03:00", 
    "title": "Complaint_Attachement.pdf", 
    "id": "17d413e8396349a789e40006c408a4e0"
  }
}

