GET /api/2.3/auctions/6428763175bc491b9514dc7de4771281/complaints HTTP/1.0
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "dateModified": "2016-09-16T16:17:43.827070+03:00", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pdf", 
          "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f6f09773f00e4ca2818ab9fbc4684b9a?KeyID=278be238&Signature=s1NEMOHGFrqM%252BoH9%252BBMl6WrkM1Hd6OpcukJw%252BL4cmc8nDP%252BP6HhmOcZPUOyS%252Bj%252Bvz38f9mlK6OThxb3k37b4CQ%253D%253D", 
          "author": "complaint_owner", 
          "documentOf": "tender", 
          "datePublished": "2016-09-16T16:17:43.827024+03:00", 
          "title": "Complaint_Attachement.pdf", 
          "id": "fd1a6c26a5c843bf8720661fc4146b31"
        }
      ], 
      "description": "complaint description", 
      "title": "complaint title", 
      "dateSubmitted": "2016-09-16T16:17:43.925321+03:00", 
      "complaintID": "UA-EA-2016-09-16-000001.1", 
      "date": "2016-09-16T16:17:43.929846+03:00", 
      "type": "claim", 
      "id": "d6c94c116e104a55b31c77e535e292f0"
    }, 
    {
      "status": "claim", 
      "description": "complaint description", 
      "title": "complaint title", 
      "dateSubmitted": "2016-09-16T16:17:44.001693+03:00", 
      "complaintID": "UA-EA-2016-09-16-000001.2", 
      "date": "2016-09-16T16:17:44.001670+03:00", 
      "type": "claim", 
      "id": "1fd393d1afab4cb69632391afa3712e9"
    }
  ]
}

