GET /api/2.3/auctions/2107e0c1269c4c8b8ab508c9c48bb4c2/complaints HTTP/1.0
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "dateModified": "2016-09-13T14:12:24.987697+03:00", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pdf", 
          "url": "http://public.docs-sandbox.ea.openprocurement.org/get/01d2bbf8bfe14578a9278a9a79d4c286?KeyID=3d7a7dcd&Signature=0TnbJVZrSQtnqGy6FT45sBCiE7mVGNuoyTBIrd2HKJ6gesYDQKkLdNE6C0VXrgPy0fzr1GkdiUJmmwokZsMPBg%253D%253D", 
          "author": "complaint_owner", 
          "documentOf": "tender", 
          "datePublished": "2016-09-13T14:12:24.987670+03:00", 
          "title": "Complaint_Attachement.pdf", 
          "id": "f4bee228b6064a218fe1222e3635f1cc"
        }
      ], 
      "description": "complaint description", 
      "title": "complaint title", 
      "dateSubmitted": "2016-09-13T14:12:25.067440+03:00", 
      "complaintID": "UA-EA-2016-09-13-000001.1", 
      "date": "2016-09-13T14:12:25.071256+03:00", 
      "type": "claim", 
      "id": "dc3aac65873a45df87a59d33a50ade9b"
    }, 
    {
      "status": "claim", 
      "description": "complaint description", 
      "title": "complaint title", 
      "dateSubmitted": "2016-09-13T14:12:25.137123+03:00", 
      "complaintID": "UA-EA-2016-09-13-000001.2", 
      "date": "2016-09-13T14:12:25.137103+03:00", 
      "type": "claim", 
      "id": "7ef5abf1a0444d3095a8bcb47e42f325"
    }
  ]
}

