PATCH /api/2.3/auctions/c77d552d67b44bbbb0bc871e43058fa5/complaints/8c8e30059e3442f4a04ce5ec3241499f HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-09-14T15:36:37.537838+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-09-14T15:36:37.161973+03:00", 
    "dateAnswered": "2016-09-14T15:36:37.046858+03:00", 
    "dateSubmitted": "2016-09-14T15:36:36.933653+03:00", 
    "complaintID": "UA-EA-2016-09-14-000001.4", 
    "date": "2016-09-14T15:36:37.544023+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "8c8e30059e3442f4a04ce5ec3241499f"
  }
}

