POST /api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/complaints/7e6cabcdadad45f5b402d9bc315c1a4c/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 346
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8775d3f2596f4568a8d17de7d50531ea?KeyID=3a39b727&Signature=z8%2BTb2%2BfBQKdtJUoHq3miSN%2BFOnLQKFj63Q90BMMnRNWtzVJeZ3ws%2FBkguTqi5A2IrjMJSBlty5iZCt13Qa2Bw%3D%3D", 
    "title": "ComplaintResolution.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b5f06ad8e55448b59bb76f206d676748/complaints/7e6cabcdadad45f5b402d9bc315c1a4c/documents/a4762deac4b84800a8c60d9849249706

{
  "data": {
    "dateModified": "2016-09-16T14:45:57.631432+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8775d3f2596f4568a8d17de7d50531ea?KeyID=3a39b727&Signature=PEv6%2FtwbuCc2y7nuAeYUz%252BzseIE9%252BqDU7aWgYb%252Bd1GObXWRpGsdq636qtetCKwDP3jQtDk57AsFh2Bf%2Fd1XrDg%253D%253D", 
    "author": "reviewers", 
    "documentOf": "tender", 
    "datePublished": "2016-09-16T14:45:57.631402+03:00", 
    "title": "ComplaintResolution.pdf", 
    "id": "a4762deac4b84800a8c60d9849249706"
  }
}

