PATCH /api/2.3/auctions/435c47dfcd164eb9806932cc6aec4056/cancellations/6e06cecdaaba4008952e01417fbab3ab?acc_token=977614b74e04409bbb1213e370cef636 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9c3c776f0c93466d9a91e68dfdffd5a7?KeyID=85c206d4&Signature=qSCVsM9fzHjltX9IdOII%252BLqsie0dxNIfzpU%2FFtHo0cDYuRKi2H40n4tcjdVeYTpHGffylVIX4PJ52lhtLmi8Bg%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-02T19:52:51.612074+02:00", 
        "dateModified": "2016-12-02T19:52:51.612100+02:00", 
        "id": "9bee4bf9277e41a3b8f4374983691241"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/2a052253699848a6b2083ef073d696d9?KeyID=85c206d4&Signature=79Ne%2FaoDPSLAIzMEp5WhHNPiAbYHI1SzT56GuKPNpHY6zbZDWh1WkJvfWPhe6ZqmO37jEHp1fnTskoOuChMIAw%253D%253D", 
        "title": "Notice-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-02T19:52:51.612074+02:00", 
        "dateModified": "2016-12-02T19:52:51.884121+02:00", 
        "id": "9bee4bf9277e41a3b8f4374983691241"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2016-12-02T19:52:52.066503+02:00", 
    "cancellationOf": "tender", 
    "id": "6e06cecdaaba4008952e01417fbab3ab"
  }
}

