PATCH /api/2.3/auctions/bbc1fa45fd914ed9911f8a5daf54e7d9/bids/026bb5de1cda4654b6f1d84aba2097e4?acc_token=a6502a0d20da47e0aa164e802b2fe7dc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

null

