PATCH /api/2.3/auctions/007f509a6dbd4f67b07d33bcad157bd5/cancellations/0f6e08182e534c0391edb83671e46c37?acc_token=293b1515fb11485080bdb821d1cb3420 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/832b0e8d8c8c4cd19001acf0ab0fb728?KeyID=58a82d14&Signature=tAYu4bVqNgYAA1%252BbcGVuiXw8mpUqnOwMUxOPOdqPJ0lW8j6YtULbROXJT8a09J12A1H4Vycbu7ZEqisDSnfNDg%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-13T15:47:21.127154+02:00", 
        "id": "46ddfa6fa0c749a19dee985884df0407", 
        "dateModified": "2017-02-13T15:47:21.127187+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8be5dbcac2314bad805b4c4a0f8f3500?KeyID=58a82d14&Signature=wii%252BFArp7lDUtP1GHYhRqat0wvLzQAl%252BWb9%252BCD3TA%252Bxkl%252B2a9pg%2FDLWQ40VrS%2FRqSycwt4WKU6w7zMTjikYdAA%253D%253D", 
        "title": "Notice-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-13T15:47:21.127154+02:00", 
        "id": "46ddfa6fa0c749a19dee985884df0407", 
        "dateModified": "2017-02-13T15:47:21.420285+02:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2017-02-13T15:47:21.580836+02:00", 
    "cancellationOf": "tender", 
    "id": "0f6e08182e534c0391edb83671e46c37"
  }
}

