PATCH /api/2.3/auctions/7c4b1c5e9c624bffa4feb0d69248e311/bids/b331976164ee46689810aef6cdbe0adb?acc_token=e420d635d98a4b3dbef4334200c4ac2a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

null

