PATCH /api/2.3/auctions/fb355202fb0045ba9367c9445be3fc75/bids/21fcd7266d6d4da7a01cab6367a05d37?acc_token=44f7c6fe9ace49ccb561def377a23eaf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

null

