POST /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/documents?acc_token=2b1b3d8fd6be4827908b19fdf46323d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 160
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "Familiarization with bank asset", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentType": "x_dgfAssetFamiliarization"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/documents/4dcb4bee7c1345aa9577789ce354296d

{
  "data": {
    "title": "Familiarization with bank asset", 
    "format": "offline/on-site-examination", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentOf": "tender", 
    "datePublished": "2018-03-13T14:17:03.845246+02:00", 
    "documentType": "x_dgfAssetFamiliarization", 
    "dateModified": "2018-03-13T14:17:03.845265+02:00", 
    "id": "4dcb4bee7c1345aa9577789ce354296d"
  }
}

