POST /api/2.3/auctions/56c507ca68744c5f964933955043072a/documents?acc_token=2ac7aaf0d5b2429e9024f281f75c0eaf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 160
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "Familiarization with bank asset", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentType": "x_dgfAssetFamiliarization"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/56c507ca68744c5f964933955043072a/documents/dfe2a9dac42c4c01a81744873cfb4c1e

{
  "data": {
    "title": "Familiarization with bank asset", 
    "format": "offline/on-site-examination", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentOf": "tender", 
    "datePublished": "2017-02-01T13:22:21.648077+02:00", 
    "documentType": "x_dgfAssetFamiliarization", 
    "dateModified": "2017-02-01T13:22:21.648133+02:00", 
    "id": "dfe2a9dac42c4c01a81744873cfb4c1e"
  }
}

