PATCH /api/2.3/auctions/0d788da874814db38bc3f67ef6f57a8b/questions/f447a55effdb4ab4b854adfb23d9703d?acc_token=3fb0279810984ff7b463b5ef6c07f04f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-09-20T17:01:07.948855+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "f447a55effdb4ab4b854adfb23d9703d", 
    "questionOf": "tender"
  }
}

