PATCH /api/2.3/auctions/a94a6fc2999f45eba3faa69f0a577d2f/questions/0d437b25b8574797b0c7ce95c108962a?acc_token=0e35fdfe8c9d45a3bdcef079068990e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-09-19T12:00:29.879928+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "0d437b25b8574797b0c7ce95c108962a", 
    "questionOf": "tender"
  }
}

