PATCH /api/2.3/auctions/435c47dfcd164eb9806932cc6aec4056/questions/0b84644e774d490e9634e8112eaf1ef6?acc_token=977614b74e04409bbb1213e370cef636 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-12-02T19:52:48.728332+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "0b84644e774d490e9634e8112eaf1ef6", 
    "questionOf": "tender"
  }
}

