GET /api/2.3/auctions/a94a6fc2999f45eba3faa69f0a577d2f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-19-000001", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/auctions/a94a6fc2999f45eba3faa69f0a577d2f", 
    "enquiryPeriod": {
      "startDate": "2016-09-12T12:00:24.493072+03:00", 
      "endDate": "2016-09-19T12:00:24.493072+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-09-19T12:36:24.493072+03:00", 
    "awardCriteria": "highestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-09-19T12:00:29.879928+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "0d437b25b8574797b0c7ce95c108962a", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "a94a6fc2999f45eba3faa69f0a577d2f", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/45bb74f9760b4d11ae893552b77f06bd?KeyID=f72c2842&Signature=ChrxhbsqiMsnsBJMr0Tk50l2EaE%252BqvLhGXU4HWDRMdRRarNWi84lOCiH6uFRQY3H3OYQxgNhS1dgCYWCYbcpDQ%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-19T12:00:29.704147+03:00", 
        "documentType": "technicalSpecifications", 
        "id": "6e9b5f4dad8044278bd4d024a1a1ff65", 
        "dateModified": "2016-09-19T12:00:29.704176+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e2ee3325c89340c689f86c16f5109bae?KeyID=f72c2842&Signature=fd%2FC%2FQnja3bKT4AkDSlKdLlcJ31RONGzbe6O9%252BLpmXuSycZaDznwUU6s8dy1tADxNQRCGISAQRxq4Ii5xLaPCw%253D%253D", 
        "title": "AwardCriteria.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-19T12:00:29.754289+03:00", 
        "dateModified": "2016-09-19T12:00:29.754316+03:00", 
        "id": "aa764a7181324de792a3499f7b5ee3fb"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9f93211818db4d63af35c1bb14761e0d?KeyID=f72c2842&Signature=%2F%2FR7VBBAf22sL7UG7yJU4BzlAz2KT%252B97Pu2vbCgvsHy0r9qaJBvxsKAdgCfQdIwExTVHyIJP%252BD1M%2FiK3mXDmBg%253D%253D", 
        "title": "AwardCriteria-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-19T12:00:29.754289+03:00", 
        "dateModified": "2016-09-19T12:00:29.808090+03:00", 
        "id": "aa764a7181324de792a3499f7b5ee3fb"
      }
    ], 
    "title": "футляри до державних нагород", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2016-09-19T12:00:30.458525+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2016-09-12T12:00:24.493072+03:00", 
      "endDate": "2016-09-19T12:00:24.493072+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-09-19T12:00:24.493072+03:00", 
      "shouldStartAfter": "2016-09-20T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "date": "2016-09-19T12:00:29.246758+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-21T12:00:24.493072+03:00", 
          "endDate": "2016-09-24T12:00:24.493072+03:00"
        }, 
        "id": "f72241d26081470bb4685f7671aa9bfc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

