GET /api/2.3/auctions/0d788da874814db38bc3f67ef6f57a8b/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a505c8ece6a64d2781396f1f47cc10e7?KeyID=87c9f4bd&Signature=Ipv2%252BgQIBebtSygD7gEnXgaDrHyGG5frza1G4YYcdCbxLI%2FTgERONqT0F8uu8jlIU%252BXedmvpjjUTwN9KDto1Aw%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-20T17:01:07.499065+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "4f3b62e2f1964facba31105c28c6d2bb", 
      "dateModified": "2016-09-20T17:01:07.499103+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d77a753ef33d4fa8b6c098edbe2adc1d?KeyID=87c9f4bd&Signature=NLma2M12tZJqHNhcpu7K%252BZPl9jKlWqpA3OJdQvsp7Hjb74LSs4sk3zyXdONWkK2rHRUcrzOvNstasjQKkUeOCQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-20T17:01:07.562057+03:00", 
      "dateModified": "2016-09-20T17:01:07.634327+03:00", 
      "id": "420a287b16924acb84cf33e8262c58a2"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/abec1aaa8133433da5a80611fa584e62?KeyID=87c9f4bd&Signature=DsLtK8zdJ7mJWpeKZoHAOdtc7fT0cKQRmgoAx03nzHFHIWxf16aZoc%252BE%252BcxAUIbJ0kS9Y7DqZOGaUYX84Xj6CQ%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-09-20T17:01:07.713121+03:00", 
      "documentType": "illustration", 
      "id": "e786b68040bd444cb8b952b17aca4861", 
      "dateModified": "2016-09-20T17:01:07.713158+03:00"
    }
  ]
}

