POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2106
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "draft", 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2018-07-25"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "DGFOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "submissionMethodDetails": "test submissionMethodDetails", 
    "dgfDecisionDate": "2016-11-17", 
    "dgfID": "219560", 
    "dgfDecisionID": "219560", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5, 
        "description": "Земля для військовослужбовців", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/0bdbbd8123854d20a2546494635ac16e
X-Content-Type-Options: nosniff

{
  "access": {
    "transfer": "38a1fca1ffd34b99af75b6cc984a16a1", 
    "token": "080510b507e64c099c9d8674c2686941"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-07-11-000002", 
    "enquiryPeriod": {
      "startDate": "2018-07-11T15:06:04.272464+03:00", 
      "endDate": "2018-07-24T23:59:50+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "awardCriteria": "highestCost", 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "id": "0bdbbd8123854d20a2546494635ac16e", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:04.272937+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2018-07-11T15:06:04.272970+03:00", 
        "id": "d36b463c1b4c44f58d8269e1978fdeb3"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "dateModified": "2018-07-11T15:06:04.276341+03:00", 
    "status": "draft", 
    "tenderPeriod": {
      "startDate": "2018-07-11T15:06:04.272464+03:00", 
      "endDate": "2018-07-24T23:59:50+03:00"
    }, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "procurementMethodType": "DGFOtherAssets", 
    "dgfID": "219560", 
    "date": "2018-07-11T15:06:04.272464+03:00", 
    "submissionMethodDetails": "test submissionMethodDetails", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "e1c679a7305f4472bb93dc175ea66a27", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

