GET /api/2.3/auctions/a94a6fc2999f45eba3faa69f0a577d2f/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/45bb74f9760b4d11ae893552b77f06bd?KeyID=f72c2842&Signature=ChrxhbsqiMsnsBJMr0Tk50l2EaE%252BqvLhGXU4HWDRMdRRarNWi84lOCiH6uFRQY3H3OYQxgNhS1dgCYWCYbcpDQ%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T12:00:29.704147+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "6e9b5f4dad8044278bd4d024a1a1ff65", 
      "dateModified": "2016-09-19T12:00:29.704176+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e2ee3325c89340c689f86c16f5109bae?KeyID=f72c2842&Signature=fd%2FC%2FQnja3bKT4AkDSlKdLlcJ31RONGzbe6O9%252BLpmXuSycZaDznwUU6s8dy1tADxNQRCGISAQRxq4Ii5xLaPCw%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T12:00:29.754289+03:00", 
      "dateModified": "2016-09-19T12:00:29.754316+03:00", 
      "id": "aa764a7181324de792a3499f7b5ee3fb"
    }
  ]
}

