PATCH /api/2.3/auctions/56c507ca68744c5f964933955043072a/contracts/74844048b04d486bb439a33f52ced316?acc_token=2ac7aaf0d5b2429e9024f281f75c0eaf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2017-02-01T13:22:24.262464+02:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/24b7b178fa7c4e1289d352a91b4ae887?KeyID=8f3407b6&Signature=YGEyKJ0MXFhzhVal0kw2kWK6zL2Y%2F3tdAFNwaC3fwKR4Gff5B1TJwyAeR3AncWmEHmTZuawhzGi9MAsMC4mADg%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-02-01T13:22:23.908010+02:00", 
        "dateModified": "2017-02-01T13:22:23.908037+02:00", 
        "id": "4e6266504c8a4dd4919ae168a3c448ed"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/492ca1a62537484f917a59164bfb40e5?KeyID=8f3407b6&Signature=PKV7TOUzgAT%2FyyTwNmLz3W3i5%252B%2FDl9t707K9jNlG3ZvnZRl1i31WFmYlLXd0Yze6kfWs8hyNjF5wwYyEO9uGCw%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-02-01T13:22:24.114143+02:00", 
        "dateModified": "2017-02-01T13:22:24.114170+02:00", 
        "id": "19c069b1851a42bcb8176222ce5ab8ec"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "04114000-0"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "schema_properties": {
          "code": "041", 
          "version": "001", 
          "properties": {
            "number_of_rooms": 4, 
            "total_area": 4
          }
        }, 
        "id": "fde9635b26524ed3b0265e1e00842537", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2017-02-01T13:22:08.972077+02:00", 
      "endDate": "2018-02-01T13:22:08.972077+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-02-01T13:22:24.262464+02:00", 
    "date": "2017-02-01T13:22:24.351661+02:00", 
    "awardID": "f3dbae5e702846c19b22e6dec43dd0c5", 
    "id": "74844048b04d486bb439a33f52ced316", 
    "contractID": "UA-EA-2017-02-01-000001-1"
  }
}

