PATCH /api/2.3/auctions/3bd2d6e4b5554f708e00eedf572994c2?acc_token=cf697c93258148169f825aed068ab794 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active.tendering"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-11-29-000001", 
    "enquiryPeriod": {
      "startDate": "2016-11-29T12:46:25.494653+02:00", 
      "endDate": "2016-12-12T23:59:50+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-12-12T23:59:50+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "3bd2d6e4b5554f708e00eedf572994c2", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2016-11-29T12:46:25.569621+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2016-11-29T12:46:25.494653+02:00", 
      "endDate": "2016-12-12T23:59:50+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-12-13T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2016-11-29T12:46:25.569621+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "43646b9a364f4489ac47334e5593a5d3", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

