GET /api/2.3/auctions/eeca007469eb4a9a8b9cd75d32289e6f/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1a292473ca1b43789f3ca225ec33d097?KeyID=1d13b7f9&Signature=VwbSykwjs7oicTNS8CdayplAALwaSicPgF7Y9S%2FBAbk1cczlY%252B8uXOp0yFY5GrTf3%2Fcyt5%2FCewUR8qgNM7k3AA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T15:13:52.104592+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "683328f6f3d74c39b8063add50c07937", 
      "dateModified": "2016-09-19T15:13:52.104626+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6e0c7d341d7b48d98ff6d5780cf20901?KeyID=1d13b7f9&Signature=jwiW%252BL9PklsYav54eRS6Uzjy0DG2g4A5tSpGDeM3HjwdwZlVUKFbQf6ONMWXOGNuHAa44lahTzGt2uqA3OhJAA%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T15:13:52.167486+03:00", 
      "dateModified": "2016-09-19T15:13:52.167529+03:00", 
      "id": "f0916e9e625a486aabceb237594bd4ad"
    }
  ]
}

