GET /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/contracts/167820e4b4ce4684944cf83b16deaf73/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/22d3b8cc510d4be880b1e16cea384c31?KeyID=e578eecc&Signature=y%252BF%252BUGdh%2FLEYDdSri%2FDCYRIxHp8gf%252BpAewKgGvNuw%252BxkBdBRauis3I8G9a%2FkV0h9TjRM1IOvFMiLlyB1uvH9AQ%253D%253D", 
      "title": "contract_first_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2018-03-13T14:17:05.462936+02:00", 
      "documentType": "prolongationProtocol", 
      "dateModified": "2018-03-13T14:17:05.462956+02:00", 
      "id": "8e9699adc2ca412eb7c9ea74a65d3ed9"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8106c4b78aed461cbb0e7ebe76e7a655?KeyID=e578eecc&Signature=kVWCHjZFpGIzqNMQSz6XeC8rB24UnK3Ur9RsFx38Hs5coEn3ekJMC31APBRo2fzQIoB2F0bV3XweXi4dwqe%2FBQ%253D%253D", 
      "title": "contract_second_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2018-03-13T14:17:05.600939+02:00", 
      "documentType": "prolongationProtocol", 
      "dateModified": "2018-03-13T14:17:05.600959+02:00", 
      "id": "1a9b1f726af546c0a56b867fa98370df"
    }
  ]
}

