GET /api/2.3/auctions/a94a6fc2999f45eba3faa69f0a577d2f/contracts/acf1ee83211947009ad709a32f3a17a7/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/fc3ba2e9758b4107ba5523432e9ef6e6?KeyID=f72c2842&Signature=cKCSU4hrLP5vItohS2EbPUlULHHFUYZEYDsss3vjKGvYDs0CjP5IXa0u6VUqjDI0EbNl6dBKoPEBcCaSUG89Cg%253D%253D", 
      "title": "contract_first_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T12:00:31.190885+03:00", 
      "dateModified": "2016-09-19T12:00:31.190911+03:00", 
      "id": "ac05ac332b894f4fb1fe5c375d4679fe"
    }
  ]
}

