POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2073
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2016-10-03T15:13:44.547333"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-21T15:13:44.547333", 
          "endDate": "2016-09-24T15:13:44.547333"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/eeca007469eb4a9a8b9cd75d32289e6f

{
  "access": {
    "token": "6b7f670ea82344f7b86f417766d3025c"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-19-000001", 
    "tenderPeriod": {
      "startDate": "2016-09-19T15:13:51.584132+03:00", 
      "endDate": "2016-10-03T15:12:44.547333+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-10-04T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-09-19T15:13:51.584132+03:00", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2016-09-19T15:13:51.588538+03:00", 
    "status": "active.tendering", 
    "awardCriteria": "highestCost", 
    "enquiryPeriod": {
      "startDate": "2016-09-19T15:13:51.584132+03:00", 
      "endDate": "2016-10-03T15:12:44.547333+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2016-10-03T15:12:44.547333+03:00", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-21T15:13:44.547333+03:00", 
          "endDate": "2016-09-24T15:13:44.547333+03:00"
        }, 
        "id": "e7a7bc6a7dc540679b989c9781c57822", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "id": "eeca007469eb4a9a8b9cd75d32289e6f", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

