GET /api/2.3/auctions/f67956e32a634f98a9ab9ad7c2b84e02/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:57.852998+02:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2016-12-21T19:57:57.853024+02:00", 
      "id": "c80a82fcc08f42fd90cd5e68c7018555"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4e905a5f66c6414dacd9d09db3c4702f?KeyID=7a220e8f&Signature=xOUgbppcfHDBRCNk9Eu1rN6mKgy9HtdXsuqYIhSklCmXSojR7SPcepQv%252BL05%252BGBUJ5ooY83l%252BE9UAfqIBMZfDA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:58.257726+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2016-12-21T19:57:58.257753+02:00", 
      "id": "40b4032222c94d56a8819e4612dbaf52"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/22e7d610dc684597854201fd917d864c?KeyID=7a220e8f&Signature=uFZx7o%2FqzMEhle%2FaK31%252BWmgKphRTPSZyNghcdS5NU0BIePdZiKDIfwT%252BJrRGtYo%252BxElGmxX39dojAeHHM%2F0LAA%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:58.314031+02:00", 
      "dateModified": "2016-12-21T19:57:58.370907+02:00", 
      "id": "20338b390a974fb9a492bff279e4abc3"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a0feb7183ecb4d94a4005a7a44ff5913?KeyID=7a220e8f&Signature=V4MLY0jPusmPEmCv%2Fu8mtBTQOG7OaCRT2hEyvbQ5JK91PveDeBAYLW7O64Rl3tF5l7Jo4KdsEW6PfgqLDeqHCA%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:58.441225+02:00", 
      "documentType": "illustration", 
      "dateModified": "2016-12-21T19:57:58.441268+02:00", 
      "id": "fa35dad76ed74a60b0fc810ac2565a0a"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3958a97b57a145a8abaa55751f55210e?KeyID=7a220e8f&Signature=hgbT6QsCTZcTKOG6d2bqN%2F5b7EYQCKhsOy2X%252BphItwrDTtZWpOzoOh1dKZJbsQtjGwAFeXF9mwNA98mmD9HcAQ%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:58.524312+02:00", 
      "documentType": "illustration", 
      "dateModified": "2016-12-21T19:57:58.524339+02:00", 
      "id": "125e2360b82d41ea893599d17a1a2e58"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c4b484b4e7564033be8bcd52576dc9ab?KeyID=7a220e8f&Signature=2X7vQ8Tg6nJ%2FM0foIL6aIv0xcKhqd2MzjhUj33wbrq5PwWHKbmTsUmIeGBYVNaYkHBDSMzz%252BibfRU4jy%2F8i8Bw%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:58.584576+02:00", 
      "documentType": "illustration", 
      "dateModified": "2016-12-21T19:57:58.584604+02:00", 
      "id": "dcf1796f235e4e00ba3428c878527136"
    }, 
    {
      "title": "Familiarization with bank asset", 
      "format": "offline/on-site-examination", 
      "accessDetails": "Familiar with asset: days, time, address", 
      "documentOf": "tender", 
      "datePublished": "2016-12-21T19:57:58.660410+02:00", 
      "documentType": "x_dgfAssetFamiliarization", 
      "dateModified": "2016-12-21T19:57:58.660437+02:00", 
      "id": "d785415532ee4f9cb472305aa2a3328e"
    }
  ]
}

