PATCH /api/2.3/auctions/d2c7b6fb8a074928820d365c09c5c0b1/documents/56f6c2d45c764c31a175350489ab70cb?acc_token=aa7d6019a2c1429fb7d3efa2431e2162 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description modified", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0dbcd2ff406b48728eca062909f64f89?KeyID=644e75be&Signature=moFkhiZy6%252BxgJZTpVbhJszhPuhVb2ac6qu5pgAmezfgBX6Nn6YWDebck%2Ft8xk9UqPTuJkxERD3UbH9hNkbi0AQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-14T15:36:47.892053+03:00", 
    "documentType": "technicalSpecifications", 
    "id": "56f6c2d45c764c31a175350489ab70cb", 
    "dateModified": "2016-09-14T15:36:47.892105+03:00"
  }
}

