GET /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/documents/96d79d45b88240f49fd044b0a9127472 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4af34c520df44c7781f6a526fdc2adb7?KeyID=e578eecc&Signature=YUkX7eiSr%252B2Z84m9kFFgCBr%2Fhyf10dc80HRbjQEhACK8Deh%2Fptc828AUsGttsQf7XPWYrRLUl9C7KdxS2r2QBg%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-03-13T14:17:03.546774+02:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2018-03-13T14:17:03.546793+02:00", 
    "id": "96d79d45b88240f49fd044b0a9127472"
  }
}

