GET /api/2.3/auctions/d929d58e6d6d432991f2dac38853e07d/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c993d913ba5e4033beb27f18fb961615?KeyID=08eb86ec&Signature=ZN4Etoug1Oko9u8w0xHUoU6pC%2FgECPncnXs6SrcwLEVbTikdjroR3%2FpcitgHpYVvq%252BoRyA7vO%2FRfmN4z82riCA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-20T12:39:33.200858+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "5c6175f37b534cc1877848b472bc5204", 
      "dateModified": "2016-09-20T12:39:33.200888+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/702a943daf594318ba23dbf0139a68e3?KeyID=08eb86ec&Signature=aYxWTfol0MjfYENaV9f2dDWlwMYW9mS4o6iLsT%2FRj7Ta2QoEpXAPMwuIA%252BweP8AnoPEefBH%2Fa0Z7tKL9R2woBQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-20T12:39:33.258474+03:00", 
      "dateModified": "2016-09-20T12:39:33.316419+03:00", 
      "id": "e981c9fbc7074032ac58adbca650ca69"
    }
  ]
}

