POST /api/2.5/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2096
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2018-07-11T15:11:02.303178"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "DGFOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "submissionMethodDetails": "quick", 
    "dgfDecisionDate": "2016-11-17", 
    "mode": "test", 
    "dgfDecisionID": "219560", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5, 
        "description": "Земля для військовослужбовців", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "dgfID": "219560"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/797cf4dd34e04e929cdb889049f2b693
X-Content-Type-Options: nosniff

{
  "access": {
    "transfer": "b95ce8b0eafb47c988cd6fce5cdc8588", 
    "token": "923d6d6f771649ad9fd7609138778833"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-07-11-000002", 
    "enquiryPeriod": {
      "startDate": "2018-07-11T15:06:04.630759+03:00", 
      "endDate": "2018-07-11T15:10:14.343245+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2018-07-11T15:10:14.343245+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "title_en": "[TESTING] ", 
    "id": "797cf4dd34e04e929cdb889049f2b693", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:04.631073+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2018-07-11T15:06:04.631095+03:00", 
        "id": "8ca456ee511141158b3634d1f5447912"
      }
    ], 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2018-07-11T15:06:04.633363+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-07-11T15:06:04.630759+03:00", 
      "endDate": "2018-07-11T15:10:14.343245+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-07-11T15:10:14.343245+03:00"
    }, 
    "procurementMethodType": "DGFOtherAssets", 
    "dgfID": "219560", 
    "date": "2018-07-11T15:06:04.630759+03:00", 
    "submissionMethodDetails": "quick", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "74fd2ae528af418fa56629aea6d8a908", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] ", 
    "awardCriteria": "highestCost"
  }
}

