GET /api/2.3/auctions/2077a4e50e744ab6bc3936e6a0bb77a0/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5d82733257fa465f9cc1d26b9cff7bbc?KeyID=c414de0e&Signature=PDw3gqBBi2FrR2Y5ZfSRQ%2FlYZ1TlKFqMfHd%252By%252BsMybKIu6lN0KbP1A3liC31xRIkgdDuVuNwEkXKHyk2Fav9Ag%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-11-25T12:16:18.878147+02:00", 
      "documentType": "technicalSpecifications", 
      "id": "3c2a03b0e30b451fa330644a6e11681e", 
      "dateModified": "2016-11-25T12:16:18.878180+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e5b8c1a1179d457caed1c849066fb38a?KeyID=c414de0e&Signature=8UFGovRAvp8H%252B%2FJwl6dAcSmpTghsebOIhaGuTTA248WrwH2ZMclR1dw3jUSzI8ondMcAncWpR8AkN%252BE1Bbs%252BDA%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-11-25T12:16:18.933210+02:00", 
      "dateModified": "2016-11-25T12:16:19.005152+02:00", 
      "id": "776400188dc643828782dae4c55d900f"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5e09d54860b949e88c104ab143ca1b0d?KeyID=c414de0e&Signature=uiAE8njuYlf6Zmgh56oE%2FE5Ah5A8O%2FoyS94ONTBNvpdkEBvhjPHYXsSNfSb1AdHZXF%2FqEhPpVtccRlTcjSGABw%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-11-25T12:16:19.085006+02:00", 
      "documentType": "illustration", 
      "id": "dbe32038546b493cac503a111594a25c", 
      "dateModified": "2016-11-25T12:16:19.085033+02:00"
    }
  ]
}

