GET /api/2.3/auctions/9bd320f850e64a18a397c41f1d5a8bd5/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:45.175627+02:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-01-31T17:28:45.175653+02:00", 
      "id": "7ff827e2a8854155906a9a29fba4f1f4"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/464eeac23334464d9b01002e11bbf7cf?KeyID=16e6e499&Signature=j91cuH8k3ukT7qWS6rpiOheEPB6K6IbTQF9i2U4XflrBC3AR7HC7TM%2Fgy2Mgi1VNzxrCKSIR2ouX%252BTB0%2FUdlDQ%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:45.703506+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-01-31T17:28:45.703540+02:00", 
      "id": "fbe475e77b354f5586bd6e22c6d538a6"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/391ec88cdd1e444bb3fb365c6aacebae?KeyID=16e6e499&Signature=bte3CFCfKeLch%2FnKni6nBuM82u7ZJSn8cCyEmcIbeZ2lU7rqSwHfgNX5J4Ycgzszrnl%252BbzTYtxx18PoLe3wKDQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:45.780371+02:00", 
      "dateModified": "2017-01-31T17:28:45.866941+02:00", 
      "id": "77c7533d76614a2cb44bca00937b192a"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/aa7975454c3d4998817da6025ff88370?KeyID=16e6e499&Signature=avXtdtns28KgdfnKObIXxZGsWrdvJUbQZTPO12KUWDo0gMW0h2EhO2YOL4%252BZ612rPKf8O8B%252BqyV3FxQNCTNHDQ%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:45.949426+02:00", 
      "documentType": "illustration", 
      "dateModified": "2017-01-31T17:28:45.949453+02:00", 
      "id": "013fecd03f484cdcb9863879016000c3"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9e35112eade2458282bbda1adf6aaa69?KeyID=16e6e499&Signature=4zGjymdqJ1OfkMM%252BIR3LNb6em2J0zni3SVNsmpFc0S%252B4K3N0glKUMOP5%2FH2OgEjgCtc2ExjRN6BNdk2JpKnlDQ%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:46.047326+02:00", 
      "documentType": "illustration", 
      "dateModified": "2017-01-31T17:28:46.047363+02:00", 
      "id": "f8303f00e4fe4e6b8bd5d77890797108"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ef99a61c9f3149798c5b8978bb0a9284?KeyID=16e6e499&Signature=rN3ZLuxHmJyhqV1LcmRbefTGEEHypCOwSE2Qr8u2N33XhHzWFVDPdnkA1xF3RdQWTZksOqqm2jSex%2FzKkWJODQ%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:46.123876+02:00", 
      "documentType": "illustration", 
      "dateModified": "2017-01-31T17:28:46.123904+02:00", 
      "id": "63e1151f7f1748a2a0bc48b0b6082744"
    }, 
    {
      "title": "Familiarization with bank asset", 
      "format": "offline/on-site-examination", 
      "accessDetails": "Familiar with asset: days, time, address", 
      "documentOf": "tender", 
      "datePublished": "2017-01-31T17:28:46.231774+02:00", 
      "documentType": "x_dgfAssetFamiliarization", 
      "dateModified": "2017-01-31T17:28:46.231799+02:00", 
      "id": "07588ad7d6cb4e6ea0acc420a0a8ddff"
    }
  ]
}

