PATCH /api/2.3/auctions/5573af0bada64bdbbe73e4372ae46a32/contracts/1b42e41bd47f44859f51f49eefdd9aa3?acc_token=ffdada9a59754aeca6b4fd1604b29147 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2016-09-16T16:17:59.416648+03:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5bf6c3d5fda5476da629d36b82a07d32?KeyID=838a2d27&Signature=qMnuaBCv9NCn%252BprPg2A8YMgSoSyfe%252BJVQ5Up344N4M1N4CswpIrHSR7exAfr6gzXPyX5E6Ko%2FxYgIQxV%2FDnDCw%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T16:17:59.095631+03:00", 
        "dateModified": "2016-09-16T16:17:59.095685+03:00", 
        "id": "a5953b409ef64132a7207fc306e171e8"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b513efec9aa745e4b226e382fbfad31d?KeyID=838a2d27&Signature=vkUAtoHvvWivigsfy7aVNnEzlTF4H9Z1tXvivziV2M7ONUKATQca4eF%252BjEihFxX08GdABYmpE0rc0vYuhUfEBg%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2016-09-16T16:17:59.272270+03:00", 
        "dateModified": "2016-09-16T16:17:59.272299+03:00", 
        "id": "23af68da63414265afb0fb3997860fb5"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-18T16:17:40.438241+03:00", 
          "endDate": "2016-09-21T16:17:40.438241+03:00"
        }, 
        "id": "e6bbd40959494e0786509ce2903eb9f0", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2016-09-16T16:17:40.440370+03:00", 
      "endDate": "2017-09-16T16:17:40.440370+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-09-16T16:17:59.416648+03:00", 
    "date": "2016-09-16T16:17:59.506143+03:00", 
    "awardID": "82737db4cafe4bfc978d80ecde647b72", 
    "id": "1b42e41bd47f44859f51f49eefdd9aa3", 
    "contractID": "UA-EA-2016-09-16-000001-1"
  }
}

