PATCH /api/2.3/auctions/a97b827bd54f4602bd98cbd02c47a4df/documents/080634695de7400b99db4f678501e93f?acc_token=9b341302885949b1a3980d7d96d0cd07 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description modified", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6f5343cabdfb44a6ba64f856ae38aafc?KeyID=520d112c&Signature=X8g8r%252BwFCkF3CXlGufW35x4AGurPdmUYfjJIRwRzTVmaqlfgeroMYqZLcvVaaVczIJMcXX4vQW01j92PXNxKBA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-09T19:51:52.432553+03:00", 
    "documentType": "technicalSpecifications", 
    "id": "080634695de7400b99db4f678501e93f", 
    "dateModified": "2016-09-09T19:51:52.432608+03:00"
  }
}

