PATCH /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/contracts/538cb657fbe54c93973e858feffa3dec?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2018-07-11T15:06:10.900112+03:00"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "prolongations": [
      {
        "status": "applied", 
        "decisionID": "ZM-937-99-92", 
        "description": "Prolongation description", 
        "datePublished": "2018-07-11T15:06:02.303212+03:00", 
        "reason": "other", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "description": "content_with_prolongation_data", 
            "format": "application/pdf", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/cd21460130854aebaa3706c137ac1d9b?KeyID=172d32c8&Signature=O%2FzNlUmCYhxxyhquaaU61uu7KTePQJsk93f9n0mu63TPpO4J%2Fc0DPjukind8shAJcOSAf7tTgB8NT1zPbPXyDw%253D%253D", 
            "title": "ProlongationDocument.doc", 
            "documentOf": "tender", 
            "datePublished": "2018-07-11T15:06:10.305330+03:00", 
            "documentType": "prolongationProtocol", 
            "dateModified": "2018-07-11T15:06:10.305361+03:00", 
            "id": "60bfda57b0844971a14ac7dabd950f4e"
          }
        ], 
        "dateCreated": "2018-07-11T15:06:01.969656+03:00", 
        "id": "22c7acbefec94ec6b8c4b1ad6807a078"
      }, 
      {
        "status": "applied", 
        "decisionID": "ZM-937-99-92-2", 
        "description": "Long prolongation description", 
        "datePublished": "2018-07-11T15:06:02.303227+03:00", 
        "reason": "other", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "description": "content_with_prolongation_data", 
            "format": "application/pdf", 
            "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f4ad6c106f6c4184bf812be2025e438e?KeyID=172d32c8&Signature=g7WWF%2FKSpXzPjRxD2wpet8scNkNCRE%2FNxccqW7Shk4CqmN1i%252Blig00sv80Kuvl0EXTBk3UBjI2umKuFZ8jL7CQ%253D%253D", 
            "title": "LongProlongationDocument.doc", 
            "documentOf": "tender", 
            "datePublished": "2018-07-11T15:06:10.675174+03:00", 
            "documentType": "prolongationProtocol", 
            "dateModified": "2018-07-11T15:06:10.675194+03:00", 
            "id": "4e70262362014335b439cd227e5de663"
          }
        ], 
        "dateCreated": "2018-07-11T15:06:01.969656+03:00", 
        "id": "eb7e1d4d47c041c0882cd91c00952c65"
      }
    ], 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/46cb517bd7684c1a9779bc6c6b61aa3b?KeyID=172d32c8&Signature=XvKnw4LjI6hr76DvKNP0ErxWYsLQfH2zRLwnDcs056LoQkSA92m2ch1bsVlfVzGADUyXv4zaoFuwEJMtnVN%252BCQ%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:09.858414+03:00", 
        "dateModified": "2018-07-11T15:06:09.858435+03:00", 
        "id": "ed5631e083de4bb78654b925d57868b5"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/91892b0c6fed455bb136447fb6f9e03c?KeyID=172d32c8&Signature=LNrfV4IvqjUYzlQKQB6degrvA%2FNfGIS%2FgbgbF09lzg26JZ%2FGx8kh7iwpJ7R%2Fxu5YB51EVq%2F5j7GaC2thrQXbDA%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:10.026475+03:00", 
        "dateModified": "2018-07-11T15:06:10.026498+03:00", 
        "id": "bf57bef28c0548d7aac002e48b85d4a1"
      }
    ], 
    "signingPeriod": {
      "startDate": "2018-07-11T15:06:09.034064+03:00", 
      "endDate": "2018-07-11T17:18:16.277790+03:00"
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "314f1cb8d47a46009b5c9537e8974be6", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-07-11T15:06:02.303178+03:00", 
      "endDate": "2019-07-11T15:06:02.303178+03:00"
    }, 
    "dateSigned": "2018-07-11T15:06:10.900112+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-07-11T15:06:10.997720+03:00", 
    "awardID": "3d052a44e86147129b0b01e3cbec1c14", 
    "id": "538cb657fbe54c93973e858feffa3dec", 
    "contractID": "UA-EA-2018-07-11-000002-1"
  }
}

