GET /api/2.3/auctions/5573af0bada64bdbbe73e4372ae46a32/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f85a5134d1d74e628cc5e995da6059bc?KeyID=838a2d27&Signature=5IXDYG52KHFR%252Bor5FzA2xMbAuPYIdAVMyTWgTQbFZEEUAWMxqS7ywTLd8PDumkOFqu%2FDWQEs4CH%2Fa%252Br4pU27CA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-16T16:17:57.105481+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "1a8dfa8acee64f52bbe8e45b55b7b85b", 
      "dateModified": "2016-09-16T16:17:57.105518+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/032691d37a5c46168395fa35ccb936fa?KeyID=838a2d27&Signature=Iv%252BvbMODFJDl1O249mmUbVKq8EgVVMPCMqFwZ9TPm2TGo2PR9ChYuGBlYCC3XKBeBAWyU%252BHAt52TqB9Kww9sBg%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-16T16:17:57.257203+03:00", 
      "dateModified": "2016-09-16T16:17:57.332420+03:00", 
      "id": "18b33a0bb4054886b6ad5ac97c239678"
    }
  ]
}

