GET /api/2.3/auctions/435c47dfcd164eb9806932cc6aec4056/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2016-12-02T19:52:47.793624+02:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2016-12-02T19:52:47.793649+02:00", 
      "id": "5ffcb6d30b7a47c1b59081c72aee2433"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/db494759bff949ccb54b8bb80dc33d55?KeyID=85c206d4&Signature=rdprbJNUAHw2SwEldlILjwKT0XkqEs5wYditwRlhDdlM4ufXysJL23MWQzZkgelH1jyiDt0LIpkr%2F0b1kltXCA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-12-02T19:52:48.221056+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2016-12-02T19:52:48.221087+02:00", 
      "id": "f844191f5cd74f1198fc878c5653b259"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e29ad8f5ce8c4c2f818cdb9ee69263d2?KeyID=85c206d4&Signature=UuJq6sfk4D%252BSPmJGyJPg7EobdikHhpoF2TmWKag0BynR9ZnvkMJwNTRl2B363rsiAzPK5IDcn5pswqB1BI8cCg%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-12-02T19:52:48.274998+02:00", 
      "dateModified": "2016-12-02T19:52:48.333345+02:00", 
      "id": "89f5f87cc3cb485298bba05aa7d80c95"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b514ab3c625e4f09bcb8639838af4c44?KeyID=85c206d4&Signature=5WTD8c6jFWS96IfwcaQEr5F2dnw89rrVqK%2FAdzKq%252B4XRJqvwU5vd4fbAvBR4naBkIgy1cpnlOWEjejmxTmRyDg%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-12-02T19:52:48.409659+02:00", 
      "documentType": "illustration", 
      "dateModified": "2016-12-02T19:52:48.409687+02:00", 
      "id": "fcb4fdfa1a4e4e9fa82f777466bb4dd4"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/80718d2babf5470b82b6f2ed9ad9e10c?KeyID=85c206d4&Signature=Wo0xr08n78HVx0cxiGejhuyskqa2pqIKTtTcrcgxHexfZak52DhMgQqBA0cK4tHD%2FsdC7fwRRpOOeOqGq2qNDQ%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-12-02T19:52:48.481565+02:00", 
      "documentType": "illustration", 
      "dateModified": "2016-12-02T19:52:48.481592+02:00", 
      "id": "bebadb4356274cd08acd429ff473294d"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0cfae156ce6c4dae98505f1270df111a?KeyID=85c206d4&Signature=V96b25Swde86ltgSoloptiKgh4QZ4onjdyBkssnho5ymt9un%252BDpz%252BAhsh3jEBmDF0ADwfE9DYx%252Bf%252BdDcaHT5CA%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2016-12-02T19:52:48.552760+02:00", 
      "documentType": "illustration", 
      "dateModified": "2016-12-02T19:52:48.552791+02:00", 
      "id": "4ac3ab2432e84879b3db6afbe62d662e"
    }
  ]
}

