GET /api/2.3/auctions/92b74c258aa344d2810c14e9946728d0/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-06-09T15:09:00.525896+03:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-06-09T15:09:00.525926+03:00", 
      "id": "76b99275e7794bb7a98fe5672915d44d"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/da6b8ce61e034c44980b7990366402ad?KeyID=dd67d497&Signature=JvA7XMqmBtKn0R5Os43yBMiDC2AR%252BFNYsXl5L%252BpKoEGfZ0bOKIGe0fo1f6sLw4Ij9cTnL39qbC8vDTLi4sfvBA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-09T15:09:00.919847+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-06-09T15:09:00.919868+03:00", 
      "id": "5c778078638b475b94f511fa79dd63ef"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/63b138c8bcb94e1b944faa492832cec7?KeyID=dd67d497&Signature=Owc4QNAnm%252Bdq%252Bs0QdL1xeZfE6zV0BBCGGQ7Ak9YndQQ6Vs7gqsBU0GzaerhFWlO9K%2FPUTS6VaafS7v9dcmI2CQ%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-09T15:09:00.968887+03:00", 
      "dateModified": "2017-06-09T15:09:00.968908+03:00", 
      "id": "fade6817e87a452cbb6694eee57eb84c"
    }
  ]
}

