PATCH /api/2.3/auctions/3a65f2a2814047f698731e25fbbfbfca?acc_token=8ce904ff276848009376e2a2346fe747 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active.tendering"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-03-13-000001", 
    "enquiryPeriod": {
      "startDate": "2018-03-13T14:16:57.516157+02:00", 
      "endDate": "2018-03-26T23:59:50+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2018-03-26T23:59:50+03:00", 
    "awardCriteria": "highestCost", 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "id": "3a65f2a2814047f698731e25fbbfbfca", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2018-03-13T14:16:57.516442+02:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2018-03-13T14:16:57.516464+02:00", 
        "id": "e00ca1789e994e7a81fc1264c1ff7040"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2018-03-13T14:16:57.551805+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-03-13T14:16:57.516157+02:00", 
      "endDate": "2018-03-26T23:59:50+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-03-27T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2018-03-13T14:16:57.551805+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "85ffe420bb304faeb1406cc6f0be5871", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

