GET /api/2.3/auctions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.3/auctions?offset=", 
    "uri": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions?offset=", 
    "offset": ""
  }, 
  "data": []
}


