GET /api/2.3/auctions/f67956e32a634f98a9ab9ad7c2b84e02/documents/40b4032222c94d56a8819e4612dbaf52 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4e905a5f66c6414dacd9d09db3c4702f?KeyID=7a220e8f&Signature=xOUgbppcfHDBRCNk9Eu1rN6mKgy9HtdXsuqYIhSklCmXSojR7SPcepQv%252BL05%252BGBUJ5ooY83l%252BE9UAfqIBMZfDA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-21T19:57:58.257726+02:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2016-12-21T19:57:58.257753+02:00", 
    "id": "40b4032222c94d56a8819e4612dbaf52"
  }
}

