GET /api/2.3/auctions/9bd320f850e64a18a397c41f1d5a8bd5/documents/fbe475e77b354f5586bd6e22c6d538a6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/464eeac23334464d9b01002e11bbf7cf?KeyID=16e6e499&Signature=j91cuH8k3ukT7qWS6rpiOheEPB6K6IbTQF9i2U4XflrBC3AR7HC7TM%2Fgy2Mgi1VNzxrCKSIR2ouX%252BTB0%2FUdlDQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-01-31T17:28:45.703506+02:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-01-31T17:28:45.703540+02:00", 
    "id": "fbe475e77b354f5586bd6e22c6d538a6"
  }
}

