POST /api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/contracts/bff4715b4894460bb42ebc11645849c9/documents?acc_token=aca8b1f9f9574f34a0942083cb65db8b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 349
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b408058b290246beb21e34cca4433b9b?KeyID=e10a37aa&Signature=Jen13M9nxmK79CTbFkGAGD4wipVJLFaduR6TKq0Fsvp%2Fsjqsy6N5MSG%2F26reQu2Amfyv06oHGy55LpjimMTtBw%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/contracts/bff4715b4894460bb42ebc11645849c9/documents/aa7310fa40314299945f12f7119d7cda

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b408058b290246beb21e34cca4433b9b?KeyID=e10a37aa&Signature=ikE9RT0mxdklkLBv%2F%252BH5x8ZaGkupYErzb4TnoME7AYy5gReqsqEo0MAS%252BHVQTbOh2%2FzDtVSp9RPAe%252Bpx%252BF2BAw%253D%253D", 
    "title": "contract_first_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2017-02-13T20:30:25.633313+02:00", 
    "dateModified": "2017-02-13T20:30:25.633357+02:00", 
    "id": "aa7310fa40314299945f12f7119d7cda"
  }
}

