GET /api/2.3/auctions/56c507ca68744c5f964933955043072a/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-02-01T13:22:19.999323+02:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-02-01T13:22:19.999372+02:00", 
      "id": "3136ee8064c24ef4ab8555d430927ebd"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f4f48d70db344310bf2a407d6f6dea95?KeyID=8f3407b6&Signature=xCrpwggqDZU87cDDCGMXMrX2rqIp3XcKD5%2FWi0t01noV%2FaZhV1xeZmzjAzlrLy5SQPcc%252BWv4sI9gN664KXnQBw%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-02-01T13:22:20.587044+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-02-01T13:22:20.587093+02:00", 
      "id": "d24959c19c6544039ba215721fc188d7"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/72309f80c9c34b5bb4333834f1512188?KeyID=8f3407b6&Signature=g4SOcSX5%252BTz3HyoRG6Wanx2r2rYAQTBVH3WV8YJjY13WWQXIc%252BEHHuehiaCWFFq5TXCcpdcRdKvNzYwsHr4hDQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-02-01T13:22:20.734187+02:00", 
      "dateModified": "2017-02-01T13:22:21.110477+02:00", 
      "id": "91240c87090242658d9158df422f0656"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/706d73b92a65446199d1d0573963d601?KeyID=8f3407b6&Signature=AUG0Ux1M3qgW8e1mtYzVaHy55h1MSBWrP9V%2Fy9SbMmwnzRYTSU3f0FP%2FuW%2FmGCpZhDj4zfyx6Dh6bfp8ByQcAw%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-02-01T13:22:21.233533+02:00", 
      "documentType": "illustration", 
      "dateModified": "2017-02-01T13:22:21.233582+02:00", 
      "id": "e7803c183b6e4ec9a45529d5b5896b21"
    }
  ]
}

