PATCH /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/contracts/167820e4b4ce4684944cf83b16deaf73?acc_token=2b1b3d8fd6be4827908b19fdf46323d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2018-03-13T14:16:55.353656", 
      "endDate": "2019-03-13T14:16:55.353656"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "signingPeriod": {
      "startDate": "2018-03-13T14:17:04.704323+02:00", 
      "endDate": "2018-03-13T14:37:13.159878+02:00"
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "0e9f197b5c394f2791241ec770c6bed3", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-03-13T14:16:55.353656+02:00", 
      "endDate": "2019-03-13T14:16:55.353656+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-03-13T14:17:05.194426+02:00", 
    "awardID": "e2afb4cd836c44c8a2fc40b48ad81b19", 
    "id": "167820e4b4ce4684944cf83b16deaf73", 
    "contractID": "UA-EA-2018-03-13-000001-1"
  }
}

