GET /api/2.3/auctions/d2c7b6fb8a074928820d365c09c5c0b1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-14-000001", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/auctions/d2c7b6fb8a074928820d365c09c5c0b1", 
    "enquiryPeriod": {
      "startDate": "2016-09-07T15:36:32.584199+03:00", 
      "endDate": "2016-09-14T15:36:32.584199+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-09-14T16:12:32.584199+03:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-09-14T15:36:48.282530+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "d33c541692814bb881ccb2fec2356fa1", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "d2c7b6fb8a074928820d365c09c5c0b1", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description modified", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0dbcd2ff406b48728eca062909f64f89?KeyID=644e75be&Signature=moFkhiZy6%252BxgJZTpVbhJszhPuhVb2ac6qu5pgAmezfgBX6Nn6YWDebck%2Ft8xk9UqPTuJkxERD3UbH9hNkbi0AQ%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:47.892053+03:00", 
        "documentType": "technicalSpecifications", 
        "id": "56f6c2d45c764c31a175350489ab70cb", 
        "dateModified": "2016-09-14T15:36:47.892105+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/320404e3f5854be783faf03ed97c6be8?KeyID=644e75be&Signature=nhoMhqJoaGptg3OwxYhtjT0jNbxlejqq0feLUKWStRQohFRXHLwRIOBnfRSy771lF9QyK5vY81a%252BtEvnT9eoBg%253D%253D", 
        "title": "AwardCriteria.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:48.089261+03:00", 
        "dateModified": "2016-09-14T15:36:48.089300+03:00", 
        "id": "ce9203d3b0d44bbc90ceb691818d4bfa"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/755cfa3191fe4bbbbb64d964bae5067e?KeyID=644e75be&Signature=KrOqazgJMISUJ2ytFtjfYrUGtXXAfpSJyFK06XHEXvO6Wy%252BSJTyRprp3HE44%2F3aNv8lIlya%2F7R71DWg%252BSt1nCg%253D%253D", 
        "title": "AwardCriteria-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-14T15:36:48.089261+03:00", 
        "dateModified": "2016-09-14T15:36:48.178271+03:00", 
        "id": "ce9203d3b0d44bbc90ceb691818d4bfa"
      }
    ], 
    "title": "футляри до державних нагород", 
    "dateModified": "2016-09-14T15:36:49.145444+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2016-09-07T15:36:32.584199+03:00", 
      "endDate": "2016-09-14T15:36:32.584199+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-09-14T15:36:32.584199+03:00", 
      "shouldStartAfter": "2016-09-15T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "date": "2016-09-14T15:36:47.492102+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-16T15:36:32.584199+03:00", 
          "endDate": "2016-09-19T15:36:32.584199+03:00"
        }, 
        "id": "86b904b3957345c2a95e321a4e07b4be", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

