GET /api/2.3/auctions/76824176310f4436a4abe3a16007ec14/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ea22dc516e184afc9bda3fe6dc2cc946?KeyID=677d21a1&Signature=fUc9l8eNFj3LyBkPp%252B0P2voYBoIpBZHYmhdN4ZEo6H61nZpLzAqXuzMaIAxZgrUas2et3cHP6SmqAeGD6GYJDw%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-13T14:12:34.744221+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "1b665749e65847fb8d3421b8fa4f4fc9", 
      "dateModified": "2016-09-13T14:12:34.744254+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6b9a67328b1143febf6c6e274d05fd37?KeyID=677d21a1&Signature=Ao6mD%2FKOuRXHgNEkuN9xU773TcJm%2FlxgmWHuz9KFW5aUUWN9L8kBSA10ZBpGogrnKehxwPymXtd9vHyKH6ixDg%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-13T14:12:35.003502+03:00", 
      "dateModified": "2016-09-13T14:12:35.069175+03:00", 
      "id": "d4363c296d34474098a332d3e4ea7fd9"
    }
  ]
}

