POST /api/2.3/auctions/4f130ddaab1f46e69ac45a15dff6a04d/contracts/dfb2323a67994034b8e7b0570c7fd65b/documents?acc_token=97871eeba234475291b2a6905fa607c6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 349
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bd3576b529c74300bd970dae47ea0e13?KeyID=54b15984&Signature=av0hhxFxnm%2FPDLFF4LUm0PihOfJaFEA7RlGDg2Bb9ofSO2u0sBvO4nF5PXSUa3IjRUHE2ikSI4u0e%2BFrg7WADw%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/4f130ddaab1f46e69ac45a15dff6a04d/contracts/dfb2323a67994034b8e7b0570c7fd65b/documents/8d0bf10f72964b829d9ce217ad7fdb12

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bd3576b529c74300bd970dae47ea0e13?KeyID=54b15984&Signature=%2FnCa4yNsDaxkR0eUIi63SF33ST6OGFz0sl9aYrLn7c7TyihuScsCZxJpBINoUWF%252BoTZfmrMWxCEpeDYl9UkFDQ%253D%253D", 
    "title": "contract_first_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2016-11-29T12:46:34.774325+02:00", 
    "dateModified": "2016-11-29T12:46:34.774351+02:00", 
    "id": "8d0bf10f72964b829d9ce217ad7fdb12"
  }
}

