GET /api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8c00eee2c9944753bcbabf37231d1ced?KeyID=e10a37aa&Signature=iPuxzyGeWBlFIru21EtuzDaOsc1S%2FBnpkavBCvqtRogeq%2FSwW3oaAcC6g92dz9OLXi7UUynN9xDen%2FLJF4OrDw%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-02-13T20:30:22.929303+02:00", 
      "documentType": "technicalSpecifications", 
      "id": "d798b9c302224d5fad9594bb25b3b828", 
      "dateModified": "2017-02-13T20:30:22.929351+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/31526e2afedd4a8bb818df6052298de7?KeyID=e10a37aa&Signature=KPxPN064oZxicN%2F6eeT6Rcf5Lx4u%252BJjwx5guvbaFmsddGl5TsR4dlyAis9RcvkzsBSI%252B2XmvHdEm8xlPh8B%252BDQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-02-13T20:30:22.987435+02:00", 
      "dateModified": "2017-02-13T20:30:23.046130+02:00", 
      "id": "de4e050392ac4a5e85d44cd9d6d17d83"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bef91a5aaa0b4d1fb05bf744ebf8820c?KeyID=e10a37aa&Signature=aoWUj0ZPSJhNL3j9CoZffcR5mK9L108calUf2jCpNvQmuqtN6sUeIctG3Y6a75TF9pBjyhUtJ5qRJ%2FKBylEBDA%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-02-13T20:30:23.119916+02:00", 
      "documentType": "illustration", 
      "id": "d6e7847e17734a6a866405b3244ceef3", 
      "dateModified": "2017-02-13T20:30:23.119950+02:00"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9d3e439e25b34b9d85eabb11c9eb79e2?KeyID=e10a37aa&Signature=%2FO%252BtY0xlRvAu8nhObcNEk60uF2ocq1a%252B%2FHlAeSCZRTEZYQA%252B41yv6dSiie5BozEO1B%252BF3Wvct8JYvGX5baDHDg%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-02-13T20:30:23.184501+02:00", 
      "documentType": "illustration", 
      "id": "25141ec6b4cd4b15b91630bd3f6b2302", 
      "dateModified": "2017-02-13T20:30:23.184528+02:00"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/662de0bf10684e129092705697c91d27?KeyID=e10a37aa&Signature=I7AAVZ726BoPTo7M%2FjyWcGMhM%252BVjkDYVbAaYl4ZQTt0eHXnebRFQexqp%252BzdyXV5HrB05d83PsIVuSH8Z3XK0CA%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-02-13T20:30:23.236910+02:00", 
      "documentType": "illustration", 
      "id": "1bc7b2202ebd4dd2bff68b110a6a196b", 
      "dateModified": "2017-02-13T20:30:23.236939+02:00"
    }
  ]
}

