GET /api/2.3/auctions/56c507ca68744c5f964933955043072a/bids/6c8100e4637f46a1b09e66a9ab06862d?acc_token=8c502f3c6f0a49d38da11b8b0b45f0dd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-01T13:22:22.345395+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "owner": "broker", 
    "id": "6c8100e4637f46a1b09e66a9ab06862d", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/56c507ca68744c5f964933955043072a?key_for_bid=6c8100e4637f46a1b09e66a9ab06862d"
  }
}

