POST /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/awards/3d052a44e86147129b0b01e3cbec1c14/documents?acc_token=5477e8a5a5c34db7a482e95104a740e8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 375
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5c0ac2965e344548876b6d8b6d371960?KeyID=172d32c8&Signature=ew8IduBTMVuhTg6yY0woelryFb9FfSsWWA5GtCgA9S2k4yfSlqFNoZF1aB5nolFOUeLWgvkKyaXKq2v0j3CbAg%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/awards/3d052a44e86147129b0b01e3cbec1c14/documents/957f127877ec4f29909a5513d284684d
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "bid_owner", 
    "title": "SignedAuctionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5c0ac2965e344548876b6d8b6d371960?KeyID=172d32c8&Signature=pngRrYy%252BznhmSUdP7PWlFLxwrL%2F7f9Q%252BZFv%252BYttuXR3x3ZFDhqsgOt6N0nT4mkQdq5ajb4Hl7sVpzW8%252BkoeDDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-11T15:06:09.350366+03:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2018-07-11T15:06:09.350387+03:00", 
    "id": "957f127877ec4f29909a5513d284684d"
  }
}

