GET /api/2.3/auctions/92b74c258aa344d2810c14e9946728d0/bids/e5b9db9881b64ed8a4dabfc9e56dbc28?acc_token=3173462756e946a5b5bd52a6f8341f59 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-06-09T15:09:01.709447+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "owner": "broker", 
    "id": "e5b9db9881b64ed8a4dabfc9e56dbc28", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/92b74c258aa344d2810c14e9946728d0?key_for_bid=e5b9db9881b64ed8a4dabfc9e56dbc28"
  }
}

