GET /api/2.3/auctions/a94a6fc2999f45eba3faa69f0a577d2f/bids/2ab83592132245ad99cbbe2c0da29acd?acc_token=fc0fde4e25844e8db86b1b39a64aae5c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2016-09-19T12:00:30.244935+03:00", 
    "id": "2ab83592132245ad99cbbe2c0da29acd", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/a94a6fc2999f45eba3faa69f0a577d2f?key_for_bid=2ab83592132245ad99cbbe2c0da29acd"
  }
}

