POST /api/2.3/auctions/435c47dfcd164eb9806932cc6aec4056/bids/def0d9534f124473bfa5c3a2e5ea0a20/documents?acc_token=5125fb9738ca49e0b157fcb412d9a863 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 377
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/fe72b419fc5b4e1fb498b4fc505117c2?KeyID=85c206d4&Signature=DzHsRdWiwLQ9gpNmz5a1VvrVrW%2BWaull4wb6YGeErKxa0OxGCi9F7rhIpsdojgTNpKW3R9u7Na8jLsabLuEtBw%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/435c47dfcd164eb9806932cc6aec4056/bids/def0d9534f124473bfa5c3a2e5ea0a20/documents/92ee67f3bd4141f18503994a4499cb1e

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/fe72b419fc5b4e1fb498b4fc505117c2?KeyID=85c206d4&Signature=ALvApbEcGNoZEUnVGDvp5kj3IsVaCpXwm8xXQE1SRI1f7VgjJ5fNRyB%2FPcAkdGaUJuXQEMAGGW9OpXdwAazMAw%253D%253D", 
    "title": "SignedAuctionProtocol.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-02T19:52:50.348998+02:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2016-12-02T19:52:50.349029+02:00", 
    "id": "92ee67f3bd4141f18503994a4499cb1e"
  }
}

