GET /api/2.3/auctions/fd2836042da3470fba3c7aa3edebaa94/bids/9ebafdca97374152ba253bfce10bcc68?acc_token=3f73f005e66f41879b480a7c4b5f6095 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/fd2836042da3470fba3c7aa3edebaa94/bids/9ebafdca97374152ba253bfce10bcc68/documents/7dd37b223ae94dd7adf9aed49cac60a0?download=403a35f2a80a418fb95b4138d4036fe2", 
        "title": "Proposal.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-02T18:39:11.842246+02:00", 
        "dateModified": "2016-12-02T18:39:11.842281+02:00", 
        "id": "7dd37b223ae94dd7adf9aed49cac60a0"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-12-02T18:39:11.668895+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "owner": "broker", 
    "id": "9ebafdca97374152ba253bfce10bcc68", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/fd2836042da3470fba3c7aa3edebaa94?key_for_bid=9ebafdca97374152ba253bfce10bcc68"
  }
}

