GET /api/2.3/auctions/eeca007469eb4a9a8b9cd75d32289e6f/bids/1ee4df99c35343a0956fa3d2699395d9?acc_token=b886b77243594d4d9ad337b0f49261b6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/eeca007469eb4a9a8b9cd75d32289e6f/bids/1ee4df99c35343a0956fa3d2699395d9/documents/caf4531d5204447a8f2b0cbca9ed82d7?download=55e125af3204481db3c2fcecb6cee6fe", 
        "title": "Proposal.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-19T15:13:53.000811+03:00", 
        "dateModified": "2016-09-19T15:13:53.000854+03:00", 
        "id": "caf4531d5204447a8f2b0cbca9ed82d7"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-09-19T15:13:52.783991+03:00", 
    "id": "1ee4df99c35343a0956fa3d2699395d9", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/eeca007469eb4a9a8b9cd75d32289e6f?key_for_bid=1ee4df99c35343a0956fa3d2699395d9"
  }
}

