GET /api/2.3/auctions/d929d58e6d6d432991f2dac38853e07d/bids/6e2b6386bc3249a594f9123f8acfb837?acc_token=5d8da80a54c4412aa6b105f04ca7d77b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/d929d58e6d6d432991f2dac38853e07d/bids/6e2b6386bc3249a594f9123f8acfb837/documents/23765cb9fb7046a8961599ced3b49d5d?download=37a5d71822ef4a7d97e33530672f31a6", 
        "title": "Proposal.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-09-20T12:39:33.926836+03:00", 
        "dateModified": "2016-09-20T12:39:33.926881+03:00", 
        "id": "23765cb9fb7046a8961599ced3b49d5d"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-09-20T12:39:33.765995+03:00", 
    "id": "6e2b6386bc3249a594f9123f8acfb837", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/d929d58e6d6d432991f2dac38853e07d?key_for_bid=6e2b6386bc3249a594f9123f8acfb837"
  }
}

