GET /api/2.3/auctions/d41ac9d44ffa4b27960f6cafb28a0cab HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2017-04-07-000001", 
    "enquiryPeriod": {
      "startDate": "2017-04-07T15:31:19.065750+03:00", 
      "endDate": "2017-04-20T23:59:50+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2017-04-20T23:59:50+03:00", 
    "awardCriteria": "highestCost", 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "id": "d41ac9d44ffa4b27960f6cafb28a0cab", 
    "eligibilityCriteria_ru": "К участию допускаются только лицензированные финансовые учреждения.", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2017-04-07T15:31:19.066097+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2017-04-07T15:31:19.066154+03:00", 
        "id": "a29bf5d8c71c4e9d94b8c3fe2f229e51"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "eligibilityCriteria_en": "Only licensed financial institutions are eligible to participate.", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-04-07T15:31:19.070221+03:00", 
    "status": "active.tendering", 
    "eligibilityCriteria": "До участі допускаються лише ліцензовані фінансові установи.", 
    "tenderPeriod": {
      "startDate": "2017-04-07T15:31:19.065750+03:00", 
      "endDate": "2017-04-20T23:59:50+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-04-21T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfFinancialAssets", 
    "dgfID": "219560", 
    "date": "2017-04-07T15:31:19.065750+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "3ad67c0ccb5140219f8793b156a6422d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

