GET /api/2.3/auctions/706c4c4a18d54e00a077064d496cb895 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-16-000001", 
    "tenderPeriod": {
      "startDate": "2016-09-16T16:23:53.936429+03:00", 
      "endDate": "2016-09-29T16:23:51.898535+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-09-30T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfFinancialAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-09-16T16:23:53.936429+03:00", 
    "dateModified": "2016-09-16T16:23:53.940055+03:00", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2016-09-16T16:23:53.936429+03:00", 
      "endDate": "2016-09-29T16:23:51.898535+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2016-09-29T16:23:51.898535+03:00", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-18T16:23:51.898535+03:00", 
          "endDate": "2016-09-21T16:23:51.898535+03:00"
        }, 
        "id": "4a526b21f1164a29a09f7af336220a5c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "id": "706c4c4a18d54e00a077064d496cb895", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

