GET /api/2.3/auctions/d2c7b6fb8a074928820d365c09c5c0b1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-14-000001", 
    "tenderPeriod": {
      "startDate": "2016-09-14T15:36:47.492102+03:00", 
      "endDate": "2016-09-27T15:36:32.584199+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-09-28T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-09-14T15:36:47.492102+03:00", 
    "dateModified": "2016-09-14T15:36:47.496083+03:00", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2016-09-14T15:36:47.492102+03:00", 
      "endDate": "2016-09-27T15:36:32.584199+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2016-09-27T15:36:32.584199+03:00", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-16T15:36:32.584199+03:00", 
          "endDate": "2016-09-19T15:36:32.584199+03:00"
        }, 
        "id": "86b904b3957345c2a95e321a4e07b4be", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "id": "d2c7b6fb8a074928820d365c09c5c0b1", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

