PATCH /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/awards/3d052a44e86147129b0b01e3cbec1c14?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "bid_owner", 
        "title": "SignedAuctionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5c0ac2965e344548876b6d8b6d371960?KeyID=172d32c8&Signature=pngRrYy%252BznhmSUdP7PWlFLxwrL%2F7f9Q%252BZFv%252BYttuXR3x3ZFDhqsgOt6N0nT4mkQdq5ajb4Hl7sVpzW8%252BkoeDDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:09.350366+03:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-07-11T15:06:09.350387+03:00", 
        "id": "957f127877ec4f29909a5513d284684d"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "auction_owner", 
        "title": "SignedAuctionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1d4542ecb8f94fb799178dcad6566b33?KeyID=172d32c8&Signature=WyV0GfpIGAm6GwAwelvkoJkJOZTtGhNtyv%2FaydlicuYrH7bdKThOjaDVlB0Gl934zP88MgvXCu5%252BGvho17%252BQBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:09.441373+03:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-07-11T15:06:09.441400+03:00", 
        "id": "f3fee195a9324d3ca36e7df794d9f226"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-07-11T15:06:09.034064+03:00", 
      "endDate": "2018-07-11T15:06:09.543619+03:00"
    }, 
    "signingPeriod": {
      "startDate": "2018-07-11T15:06:09.034064+03:00", 
      "endDate": "2018-07-11T15:26:15.444480+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-07-11T15:06:09.034064+03:00", 
      "endDate": "2018-07-11T15:06:09.543619+03:00"
    }, 
    "bid_id": "e17d3f64fe214a6b846c885cdf2aaa9b", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-07-11T15:06:09.554614+03:00", 
    "id": "3d052a44e86147129b0b01e3cbec1c14"
  }
}

