PATCH /api/2.3/auctions/92b74c258aa344d2810c14e9946728d0/awards/24e69a35e2294e8c840a9cafe9ba366f?acc_token=0be9719321be4aa699f77ec6cff48e1a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "paymentPeriod": {
      "startDate": "2017-06-09T15:09:02.157968+03:00", 
      "endDate": "2017-06-09T15:09:02.792665+03:00"
    }, 
    "documents": [
      {
        "dateModified": "2017-06-09T15:09:02.455960+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0025fb58a2124b8cac24fb2f54e7ffef?KeyID=dd67d497&Signature=5FxI3DbZnKwLO8MgmmeqqHj2pZQpSjuAOXg%252BSx34tzHJGoMlzEOLz1zCYJ94UWpWn6lbWz7xfW%2F7TsmQwyMsBQ%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-06-09T15:09:02.455938+03:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "ab8039798220483ab57576359308f952"
      }, 
      {
        "dateModified": "2017-06-09T15:09:02.550251+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/966d7b55b54943b6ad48ba8886ae5d51?KeyID=dd67d497&Signature=Sv5R7AFR1FXjBJ1ezPsEwUaaLAQYgWXOxXAZtZF0RS9HHZFk9D3uJ5LQp%2F1mIao8G4ei%2FJ20iVoGTN8gN24EDQ%253D%253D", 
        "author": "auction_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-06-09T15:09:02.550231+03:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "1a9ac66fd1734c1bbf66c98bd9a4ba03"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2017-06-09T15:09:02.157968+03:00", 
      "endDate": "2017-06-09T15:09:02.668017+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-06-09T15:09:02.157968+03:00", 
      "endDate": "2017-06-09T15:09:02.792665+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "signingPeriod": {
      "startDate": "2017-06-09T15:09:02.157968+03:00", 
      "endDate": "2017-06-09T15:29:08.448245+03:00"
    }, 
    "bid_id": "e5b9db9881b64ed8a4dabfc9e56dbc28", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-06-09T15:09:02.804772+03:00", 
    "id": "24e69a35e2294e8c840a9cafe9ba366f"
  }
}

