POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1934
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2016-10-03T12:00:24.494765"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "85c79d97046c47ca8f7e1c2b07fbb4bd", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "title_en": "Cases with state awards", 
    "mode": "test"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b1fc5e470b5a4abf99061ef551610a41

{
  "access": {
    "token": "b104f157be5f4f90a89eb0a062182ab0"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-19-000002", 
    "enquiryPeriod": {
      "startDate": "2016-09-19T12:00:29.406886+03:00", 
      "endDate": "2016-10-02T12:00:24.494765+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-10-02T12:00:24.494765+03:00", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "title_en": "[TESTING] Cases with state awards", 
    "id": "b1fc5e470b5a4abf99061ef551610a41", 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "dateModified": "2016-09-19T12:00:29.409545+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2016-09-19T12:00:29.406886+03:00", 
      "endDate": "2016-10-02T12:00:24.494765+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-10-03T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "date": "2016-09-19T12:00:29.406886+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "85c79d97046c47ca8f7e1c2b07fbb4bd", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] футляры к государственным наградам", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

