POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1934
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2016-12-09T12:16:11.241018"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "dd2cf44e06b247cdba7d17b2b759f9f7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "title_en": "Cases with state awards", 
    "mode": "test"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/99afc030042a4d4c8790ec51999a498a

{
  "access": {
    "token": "ba3e24e25c5a48cf91d57fab71f223f6"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-11-25-000002", 
    "enquiryPeriod": {
      "startDate": "2016-11-25T12:16:18.647201+02:00", 
      "endDate": "2016-12-08T20:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-12-08T20:00:00+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "title_en": "[TESTING] Cases with state awards", 
    "id": "99afc030042a4d4c8790ec51999a498a", 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "dateModified": "2016-11-25T12:16:18.649987+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2016-11-25T12:16:18.647201+02:00", 
      "endDate": "2016-12-08T20:00:00+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-12-09T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "date": "2016-11-25T12:16:18.647201+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "dd2cf44e06b247cdba7d17b2b759f9f7", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] футляры к государственным наградам", 
    "awardCriteria": "highestCost"
  }
}

