POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1934
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2017-01-04T19:57:50.354128"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "809fbce6b09b4675819376ac6b146fbd", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "title_en": "Cases with state awards", 
    "mode": "test"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/907f4d2ce59d473fad3518b6a24799d3

{
  "access": {
    "token": "0cbb5153fa0e4cc29b80d8a2103e3bd2"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-12-21-000002", 
    "enquiryPeriod": {
      "startDate": "2016-12-21T19:57:58.019123+02:00", 
      "endDate": "2017-01-03T20:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-01-03T20:00:00+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "title_en": "[TESTING] Cases with state awards", 
    "id": "907f4d2ce59d473fad3518b6a24799d3", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2016-12-21T19:57:58.019481+02:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2016-12-21T19:57:58.019510+02:00", 
        "id": "52e71ed6cebe4594a2e469587f5c8f32"
      }
    ], 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "dateModified": "2016-12-21T19:57:58.022665+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2016-12-21T19:57:58.019123+02:00", 
      "endDate": "2017-01-03T20:00:00+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-01-04T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "date": "2016-12-21T19:57:58.019123+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "809fbce6b09b4675819376ac6b146fbd", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] футляры к государственным наградам", 
    "awardCriteria": "highestCost"
  }
}

