GET /api/2.3/auctions/aec6f83699b144ff89f095545e155f6c/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a35282b6540c4f09b172ae94a1661965?KeyID=5d03ea6b&Signature=sdaI4TkkNGXIcVC%252B8o6b7bEqmRuItgeGHX2hCA%2Ffs42PyO4s%2FFgaVt5Hwl2KeY8ARRW%252BBDdJ7U3oVpnD0QgxDQ%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T12:00:27.886033+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "12cc54b47fb24aa599f5444218d79d0d", 
      "dateModified": "2016-09-19T12:00:27.886064+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9a637962c9084947bc5353a2b27f33e8?KeyID=5d03ea6b&Signature=05h4U1opHsr2YqkcbkG%252Bl1VG%2FvXvlQL9Z8RkeVrBNrzavYn7TYi7nNKj2tpYiTTFJT8wXDWkePwGWkEklWTIAw%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T12:00:27.936248+03:00", 
      "dateModified": "2016-09-19T12:00:27.992072+03:00", 
      "id": "615e45cb6f0b42368be76e4ce9b19921"
    }
  ]
}

