POST /api/2.3/auctions/fb355202fb0045ba9367c9445be3fc75/documents?acc_token=3329409db97d48a0b9d5a3ca831ee2c0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 127
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://virtial-data-room.com/id_of_room", 
    "title": "VDR for auction lot", 
    "documentType": "virtualDataRoom"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/fb355202fb0045ba9367c9445be3fc75/documents/dd86579185e644d58ad17bb72a5a124c

{
  "data": {
    "title": "VDR for auction lot", 
    "url": "http://virtial-data-room.com/id_of_room", 
    "documentOf": "tender", 
    "datePublished": "2016-09-20T12:39:31.465064+03:00", 
    "documentType": "virtualDataRoom", 
    "dateModified": "2016-09-20T12:39:31.465092+03:00", 
    "id": "dd86579185e644d58ad17bb72a5a124c"
  }
}

