GET /api/2.5/auctions/1bd0478dee5b4b0581e2d1bf7f47fa51/documents/943764a2ec944dea859f242236e32975 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1ac184ba38634610bcb878b445308360?KeyID=172d32c8&Signature=2Y%2FPNHdAQL0vHdV0Z%252BTfDTJiA8OMu8ER04jVygL4RdYIFbhgiHdKpKPT%2F7RkAJltTu8XQjZtfJOY2X0D5fZEAQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-11T15:06:06.609510+03:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2018-07-11T15:06:06.609531+03:00", 
    "id": "943764a2ec944dea859f242236e32975"
  }
}

