POST /api/2.3/auctions/5cc3dde7c79044b5abe4433a7b7f02ca/documents?acc_token=527d1ea93e934aae99d06dbd3a2bf72b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 127
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://virtial-data-room.com/id_of_room", 
    "title": "VDR for auction lot", 
    "documentType": "virtualDataRoom"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/5cc3dde7c79044b5abe4433a7b7f02ca/documents/9415bb6e97b34a0a8ef22ebd5af256fa

{
  "data": {
    "title": "VDR for auction lot", 
    "url": "http://virtial-data-room.com/id_of_room", 
    "documentOf": "tender", 
    "datePublished": "2016-11-29T12:46:30.958304+02:00", 
    "documentType": "virtualDataRoom", 
    "dateModified": "2016-11-29T12:46:30.958331+02:00", 
    "id": "9415bb6e97b34a0a8ef22ebd5af256fa"
  }
}

