POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2077
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2016-10-03T12:00:24.493072"
    }, 
    "procurementMethodType": "dgfFinancialAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-21T12:00:24.493072", 
          "endDate": "2016-09-24T12:00:24.493072"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/aec6f83699b144ff89f095545e155f6c

{
  "access": {
    "token": "f5dcffce601147e79012b0a1a450a7cb"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-19-000001", 
    "tenderPeriod": {
      "startDate": "2016-09-19T12:00:27.732518+03:00", 
      "endDate": "2016-10-03T11:59:24.493072+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-10-04T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfFinancialAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-09-19T12:00:27.732518+03:00", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2016-09-19T12:00:27.735442+03:00", 
    "status": "active.tendering", 
    "awardCriteria": "highestCost", 
    "enquiryPeriod": {
      "startDate": "2016-09-19T12:00:27.732518+03:00", 
      "endDate": "2016-10-03T11:59:24.493072+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2016-10-03T11:59:24.493072+03:00", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-21T12:00:24.493072+03:00", 
          "endDate": "2016-09-24T12:00:24.493072+03:00"
        }, 
        "id": "b39c297305b3411eae1c9e5e5c9c492f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "id": "aec6f83699b144ff89f095545e155f6c", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

