GET /api/2.5/auctions/1bd0478dee5b4b0581e2d1bf7f47fa51/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2018-07-11T15:06:06.539174+03:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2018-07-11T15:06:06.539196+03:00", 
      "id": "556fede524934437bb9007bb38802230"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1ac184ba38634610bcb878b445308360?KeyID=172d32c8&Signature=2Y%2FPNHdAQL0vHdV0Z%252BTfDTJiA8OMu8ER04jVygL4RdYIFbhgiHdKpKPT%2F7RkAJltTu8XQjZtfJOY2X0D5fZEAQ%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-07-11T15:06:06.609510+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2018-07-11T15:06:06.609531+03:00", 
      "id": "943764a2ec944dea859f242236e32975"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f2b13729f22c4cd9b2280cdcd5f3191f?KeyID=172d32c8&Signature=8OyAfdntjoU%252BLXpBecddhIHcqQtLw3wU9BERrJhUef5uwjNYmUa5gFzQAUYntmcaeHdEXb2LzcBNrI5KhMP%252BAA%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-07-11T15:06:06.664005+03:00", 
      "dateModified": "2018-07-11T15:06:06.664026+03:00", 
      "id": "6d5fced0129d424294cbd1e43f503120"
    }
  ]
}

