GET /api/2.3/auctions/e8b7de8b343844e0bb0b5d9e61256e1a/documents/0dbd867874f9426d90fe5354912328d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a60838ccbd0746d28d540a71bd7e78ad?KeyID=58509a4a&Signature=jznMh9Y1MGZI%2F3amHTrEJfBOK86iAx3PBqUplN0YQDLyYg%252B6BnViyWAsOO%2Fwl1By1XbGu264cDxos1Rnnq69BQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-21T19:57:56.484926+02:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2016-12-21T19:57:56.484954+02:00", 
    "id": "0dbd867874f9426d90fe5354912328d3"
  }
}

