GET /api/2.3/auctions/2062358d6dd34c3295109405de1815dc/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b19d6ba593ed4d609e1f9491f75ae3b2?KeyID=8ab027fa&Signature=D5fvXpytJPFtwdE8bORLHza0nGF0VUS7FcYw9K56oK7HGNMNqbjuQwTIds9j5MVbULy7v9OtTeDlXc6sJUbCDA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T15:13:48.426666+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "6265760fd73145c6b2243c7af0103d67", 
      "dateModified": "2016-09-19T15:13:48.426717+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1bea7205bcbf4e1ea826e216bf5b1dc6?KeyID=8ab027fa&Signature=TuCzfjhdidh8Ih6CV8FfqkiUHlHDCQwzPqF5orbd4cbd3Fxl1Yvf6z91RXZhb8tWfd6ctYy4DwOOopiXYrCsDw%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-09-19T15:13:48.700603+03:00", 
      "dateModified": "2016-09-19T15:13:48.734767+03:00", 
      "id": "4c80797b0f27443dae0968c52af1c90a"
    }
  ]
}

