POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1951
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2017-02-27"
    }, 
    "procurementMethodType": "dgfFinancialAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "dgfID": "219560", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "items": [
      {
        "classification": {
          "scheme": "CAV", 
          "id": "06000000-2", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5, 
        "description": "Земля для військовослужбовців", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/bbc1fa45fd914ed9911f8a5daf54e7d9

{
  "access": {
    "token": "e330b77e518e43fb8c764b7742a23eb6"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2017-02-13-000001", 
    "enquiryPeriod": {
      "startDate": "2017-02-13T15:47:16.037498+02:00", 
      "endDate": "2017-02-26T23:59:50+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-02-26T23:59:50+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "bbc1fa45fd914ed9911f8a5daf54e7d9", 
    "eligibilityCriteria_ru": "К участию допускаются только лицензированные финансовые учреждения.", 
    "title": "футляри до державних нагород", 
    "eligibilityCriteria_en": "Only licensed financial institutions are eligible to participate.", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-02-13T15:47:16.040351+02:00", 
    "status": "active.tendering", 
    "eligibilityCriteria": "До участі допускаються лише ліцензовані фінансові установи.", 
    "tenderPeriod": {
      "startDate": "2017-02-13T15:47:16.037498+02:00", 
      "endDate": "2017-02-26T23:59:50+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-02-27T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfFinancialAssets", 
    "dgfID": "219560", 
    "date": "2017-02-13T15:47:16.037498+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "6674f4eba0f14af7942068f614bbae36", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

