GET /api/2.3/auctions/acae3ff4a40b4c859542dbb5b0cbe6e5/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-06-09T15:08:59.135396+03:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-06-09T15:08:59.135421+03:00", 
      "id": "183532e1e80440b18ab0a2d30bc42552"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0cd2dc79560f4e6a891d2aba2826a143?KeyID=161d9473&Signature=RVLTvRz6Im5y8jxCMNmEul1vMbs9g4QQQAfzbzSCvBcq4cdNKsT%2F4Ln7WJwNyOyYPZcbkQf2yO4ta7SsyjA4DQ%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-09T15:08:59.287837+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-06-09T15:08:59.287859+03:00", 
      "id": "7b1c790f36e5455dbaece30b9be45da3"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/39c8ec8b9c464f56a91092a68b4371c3?KeyID=161d9473&Signature=miJhuUt4AGLmu6mS10QuuoLnY%2FUQkIqqUH4s%2FYiD%2FWI0Xb0O0%2Frh3%252BDWSu3ljj0z1IDKi2maGPD3X2z9RGpVAw%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-09T15:08:59.339857+03:00", 
      "dateModified": "2017-06-09T15:08:59.387864+03:00", 
      "id": "65e0e527509049eab2c2fb86b81bff0f"
    }
  ]
}

