GET /api/2.3/auctions/7c4b1c5e9c624bffa4feb0d69248e311/documents/7697dfe7bbb142dda6ce306d70e75a9b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/168e34b56cb646ee8450e9cdbb5cb84d?KeyID=0678eb99&Signature=lI8kxzS7AsjFS5O2fO0gdQshCcNwUxgrWmSwD7Csyak%2Fr44YOJGgrfTwPvDJdpEhNQM8JBFJTDLcIQ%2FmIvFWCA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-01T13:22:17.868599+02:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-02-01T13:22:17.868627+02:00", 
    "id": "7697dfe7bbb142dda6ce306d70e75a9b"
  }
}

