GET /api/2.3/auctions/d41ac9d44ffa4b27960f6cafb28a0cab/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-04-07T15:31:19.066097+03:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-04-07T15:31:19.066154+03:00", 
      "id": "a29bf5d8c71c4e9d94b8c3fe2f229e51"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0c72f4185cf94fc8a7fe05bdfd33c446?KeyID=00fc7a9f&Signature=mOp7tVYsf8XcLT9eNL%252BUxfGq3gMiUzra9yFjnVesPyKEFS8vhevewr4qGOtKum6fHhgPVUoNaCu7Rr%2FxcGdSAw%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-04-07T15:31:19.231811+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-04-07T15:31:19.231842+03:00", 
      "id": "06650b9ce12a4cbfae246cb2fb5f3c07"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5aaeabd58992486b8bf974678c519afc?KeyID=00fc7a9f&Signature=i4TKp1vTlKpYZS5CoyR2KOn2GsR2RtdbG9nz6bv5NYbsxONL0GDO7f4DSAyhpmU%2FvESt1ko3c6Veo5nP9ry2CQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-04-07T15:31:19.290601+03:00", 
      "dateModified": "2017-04-07T15:31:19.355254+03:00", 
      "id": "155a293ea2414b90a5ee1217b1ce9352"
    }
  ]
}

