GET /api/2.3/auctions/5573af0bada64bdbbe73e4372ae46a32/questions/9412209e588e4fa59b3c60acf2dab925 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-09-16T16:17:57.418934+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "9412209e588e4fa59b3c60acf2dab925", 
    "questionOf": "tender"
  }
}

