GET /api/2.3/auctions/f67956e32a634f98a9ab9ad7c2b84e02/questions/46cbc39eb2f24602a0fcd34c9fd4bb97 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-12-21T19:57:58.746985+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "46cbc39eb2f24602a0fcd34c9fd4bb97", 
    "questionOf": "tender"
  }
}

