GET /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "pending", 
      "paymentPeriod": {
        "startDate": "2018-03-13T14:17:04.704323+02:00"
      }, 
      "verificationPeriod": {
        "startDate": "2018-03-13T14:17:04.704323+02:00", 
        "endDate": "2018-03-13T14:21:13.826545+02:00"
      }, 
      "signingPeriod": {
        "startDate": "2018-03-13T14:17:04.704323+02:00", 
        "endDate": "2018-03-13T14:37:13.159878+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-03-13T14:17:04.704323+02:00"
      }, 
      "bid_id": "6742acc9246c45059d4f46aad4c65f1c", 
      "value": {
        "currency": "UAH", 
        "amount": 501.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-03-13T14:17:04.704323+02:00", 
      "id": "e2afb4cd836c44c8a2fc40b48ad81b19"
    }, 
    {
      "status": "pending.waiting", 
      "complaintPeriod": {
        "startDate": "2018-03-13T14:17:04.704323+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "be3bb6d966f34c7389a71bfdada36002", 
      "value": {
        "currency": "UAH", 
        "amount": 500.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-03-13T14:17:04.704323+02:00", 
      "id": "aa7678ac3df24b7f8d502e693633057e"
    }
  ]
}

