GET /api/2.3/auctions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.3/auctions?offset=2016-11-29T12%3A46%3A30.549349%2B02%3A00", 
    "uri": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions?offset=2016-11-29T12%3A46%3A30.549349%2B02%3A00", 
    "offset": "2016-11-29T12:46:30.549349+02:00"
  }, 
  "data": [
    {
      "id": "5cc3dde7c79044b5abe4433a7b7f02ca", 
      "dateModified": "2016-11-29T12:46:30.549349+02:00"
    }
  ]
}

