GET /api/2.5/auctions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "next_page": {
    "path": "/api/2.5/auctions?offset=", 
    "uri": "http://api-sandbox.ea.openprocurement.org/api/2.5/auctions?offset=", 
    "offset": ""
  }, 
  "data": []
}

