GET /api/2.3/auctions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.3/auctions?offset=2017-01-31T17%3A28%3A43.168298%2B02%3A00", 
    "uri": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions?offset=2017-01-31T17%3A28%3A43.168298%2B02%3A00", 
    "offset": "2017-01-31T17:28:43.168298+02:00"
  }, 
  "data": [
    {
      "id": "59c1a71d8b624340985fa04bb5bc427c", 
      "dateModified": "2017-01-31T17:28:43.168298+02:00"
    }
  ]
}

