GET /api/2.3/auctions/f6a8d0f1fd564397b3f1fd30ce85b004/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2017-02-15T11:48:44.839221+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "884f91f1e2624fe59fa733589b03352d", 
      "questionOf": "tender"
    }
  ]
}

