GET /api/2.3/auctions/56c507ca68744c5f964933955043072a/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2017-02-01T13:22:21.776002+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "5140218e67ee45368ac64d44b5423cf0", 
      "questionOf": "tender"
    }
  ]
}

