GET /api/2.3/auctions/9bd320f850e64a18a397c41f1d5a8bd5/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2017-01-31T17:28:46.391382+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "617789efe179477687e1bbe52b8b485e", 
      "questionOf": "tender"
    }
  ]
}

