PATCH /api/2.3/auctions/76824176310f4436a4abe3a16007ec14?acc_token=321b272f9a3842f59918ebcc118c8f17 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-09-28T14:12:44.594767+03:00"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-13-000001", 
    "auctionPeriod": {
      "shouldStartAfter": "2016-09-29T00:00:00+03:00"
    }, 
    "tenderPeriod": {
      "startDate": "2016-09-13T14:12:34.338296+03:00", 
      "endDate": "2016-09-28T14:12:44.594767+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земля", 
          "id": "70122000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-15T14:12:22.792154+03:00", 
          "endDate": "2016-09-18T14:12:22.792154+03:00"
        }, 
        "id": "f01de1e6791d45fa9f6f5d09766263f2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-09-13T14:12:34.338296+03:00", 
    "dateModified": "2016-09-13T14:12:34.653635+03:00", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2016-09-13T14:12:34.338296+03:00", 
      "endDate": "2016-09-26T14:12:22.792154+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2016-09-28T14:12:44.594767+03:00", 
    "id": "76824176310f4436a4abe3a16007ec14", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

