PATCH /api/2.3/auctions/2077a4e50e744ab6bc3936e6a0bb77a0/cancellations/6916617b6fd0449c8dc4e3693a80ee94/documents/b92a9fc10a814fa58a5dea35a43cff3c?acc_token=60ba6c1078974d43a97cf13b9c9488d4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/25a2fdb8af65486c9f62ab6ce6fa0290?KeyID=c414de0e&Signature=D50frTaYK0ahcD90Yfmla8y6MbJ%252BNsPHsHIv%252BiZHsvvLITVVNHj6w90lqJUZ%2FKVCbNcL%252BlAzBJDbvrm26ykQAQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-11-25T12:16:21.829968+02:00", 
    "id": "b92a9fc10a814fa58a5dea35a43cff3c", 
    "dateModified": "2016-11-25T12:16:21.830013+02:00"
  }
}

