PATCH /api/2.3/auctions/fd2836042da3470fba3c7aa3edebaa94?acc_token=4d8f8ce7cb75449ca654d2f83a4471d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-12-17T18:39:20.727418+02:00"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-12-02-000001", 
    "tenderPeriod": {
      "startDate": "2016-12-02T18:39:10.425688+02:00", 
      "endDate": "2016-12-15T23:59:50+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2016-12-16T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "enquiryPeriod": {
      "startDate": "2016-12-02T18:39:10.425688+02:00", 
      "endDate": "2016-12-15T23:59:50+02:00"
    }, 
    "date": "2016-12-02T18:39:10.425688+02:00", 
    "dateModified": "2016-12-02T18:39:10.429470+02:00", 
    "status": "active.tendering", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dgfID": "219560", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "owner": "broker", 
    "next_check": "2016-12-15T23:59:50+02:00", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "dd4e3b63276342239cace836b94f4b3c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "id": "fd2836042da3470fba3c7aa3edebaa94", 
    "awardCriteria": "highestCost"
  }
}

