PATCH /api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9?acc_token=aca8b1f9f9574f34a0942083cb65db8b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-02-28T20:30:32.790278+02:00"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2017-02-13-000001", 
    "tenderPeriod": {
      "startDate": "2017-02-13T20:30:22.498470+02:00", 
      "endDate": "2017-02-26T23:59:50+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-02-27T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "enquiryPeriod": {
      "startDate": "2017-02-13T20:30:22.498470+02:00", 
      "endDate": "2017-02-26T23:59:50+02:00"
    }, 
    "date": "2017-02-13T20:30:22.498470+02:00", 
    "dateModified": "2017-02-13T20:30:22.501360+02:00", 
    "status": "active.tendering", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dgfID": "219560", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "owner": "broker", 
    "next_check": "2017-02-26T23:59:50+02:00", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "59f3595441fa4cc8ac87bc83c464368c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "id": "c4dd4d72218b43df8603bf9ceffd09d9", 
    "awardCriteria": "highestCost"
  }
}

