PATCH /api/2.3/auctions/0d788da874814db38bc3f67ef6f57a8b/cancellations/2ec2f276dba84be1ace73c92fafdd894/documents/1b294806614f4a479818f4df9b9a9ff4?acc_token=3fb0279810984ff7b463b5ef6c07f04f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6efa1f3910324494b51128c858c19a61?KeyID=87c9f4bd&Signature=G4TH05zdrbmz7kA1dXDqFWXokRRVMnM0IwF46AmifQR8SavoRur3EGfY8XCBQWU0K%252B1kpRwgbwwPmk1aAJaxAg%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-20T17:01:10.513838+03:00", 
    "id": "1b294806614f4a479818f4df9b9a9ff4", 
    "dateModified": "2016-09-20T17:01:10.513867+03:00"
  }
}

