PATCH /api/2.3/auctions/a97b827bd54f4602bd98cbd02c47a4df/cancellations/51d19d8340aa4ba98dd973380ffab3a3/documents/762400065ed04becb88aa3ad8c89270e?acc_token=9b341302885949b1a3980d7d96d0cd07 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ad039be92f3c4f85bce7c9c75157e71c?KeyID=520d112c&Signature=w0FGF%252BhYRiGGxLrdKYPL39xvxmSfa7HT8i9WzycmIARqLLI%2F0U79aMImis2BD1ZlcwLm0FTY7Z1NM0vBXjwACQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-09T19:51:55.598667+03:00", 
    "id": "762400065ed04becb88aa3ad8c89270e", 
    "dateModified": "2016-09-09T19:51:55.598697+03:00"
  }
}

