POST /api/2.3/auctions/34a03244dd6642f2bcd612f434c6c913/cancellations?acc_token=5516b94f9ffc499db4da6ab04ce35f90 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/34a03244dd6642f2bcd612f434c6c913/cancellations/f3aaebf67a3e4040bfbaced5e9f6fe3a

{
  "data": {
    "date": "2016-09-16T14:46:09.937561+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "f3aaebf67a3e4040bfbaced5e9f6fe3a"
  }
}

