PATCH /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/contracts/538cb657fbe54c93973e858feffa3dec/prolongations/eb7e1d4d47c041c0882cd91c00952c65?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "applied"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "applied", 
    "decisionID": "ZM-937-99-92-2", 
    "description": "Long prolongation description", 
    "datePublished": "2018-07-11T15:06:02.303227+03:00", 
    "reason": "other", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "content_with_prolongation_data", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f4ad6c106f6c4184bf812be2025e438e?KeyID=172d32c8&Signature=g7WWF%2FKSpXzPjRxD2wpet8scNkNCRE%2FNxccqW7Shk4CqmN1i%252Blig00sv80Kuvl0EXTBk3UBjI2umKuFZ8jL7CQ%253D%253D", 
        "title": "LongProlongationDocument.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-07-11T15:06:10.675174+03:00", 
        "documentType": "prolongationProtocol", 
        "dateModified": "2018-07-11T15:06:10.675194+03:00", 
        "id": "4e70262362014335b439cd227e5de663"
      }
    ], 
    "dateCreated": "2018-07-11T15:06:01.969656+03:00", 
    "id": "eb7e1d4d47c041c0882cd91c00952c65"
  }
}

