POST /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/contracts/167820e4b4ce4684944cf83b16deaf73/prolongations?acc_token=2b1b3d8fd6be4827908b19fdf46323d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 172
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "decisionID": "ZM-937-99-92", 
    "reason": "other", 
    "documents": [], 
    "description": "Prolongation description", 
    "datePublished": "2018-03-13T14:16:55.353696+02:00"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/contracts/167820e4b4ce4684944cf83b16deaf73/prolongations

{
  "data": {
    "status": "draft", 
    "decisionID": "ZM-937-99-92", 
    "description": "Prolongation description", 
    "dateCreated": "2018-03-13T14:16:54.838196+02:00", 
    "reason": "other", 
    "datePublished": "2018-03-13T14:16:55.353696+02:00", 
    "id": "762193c7c2214c079849888f32cdc4dd"
  }
}

