POST /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/contracts/538cb657fbe54c93973e858feffa3dec/prolongations/22c7acbefec94ec6b8c4b1ad6807a078/documents?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 440
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "content_with_prolongation_data", 
    "title": "ProlongationDocument.doc", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/cd21460130854aebaa3706c137ac1d9b?KeyID=172d32c8&Signature=iBGMtFVPcxjwLQS%2B1XymFi9uNV2G1hWEFRtJ%2BYXylcEIRiYyQ9fy8ZI%2B%2FbX%2F%2FUNHwTbywemLWThl9ijrtjUjCA%3D%3D", 
    "format": "application/pdf", 
    "documentType": "prolongationProtocol"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/contracts/538cb657fbe54c93973e858feffa3dec/prolongations/22c7acbefec94ec6b8c4b1ad6807a078/documents/60bfda57b0844971a14ac7dabd950f4e
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "content_with_prolongation_data", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/cd21460130854aebaa3706c137ac1d9b?KeyID=172d32c8&Signature=O%2FzNlUmCYhxxyhquaaU61uu7KTePQJsk93f9n0mu63TPpO4J%2Fc0DPjukind8shAJcOSAf7tTgB8NT1zPbPXyDw%253D%253D", 
    "title": "ProlongationDocument.doc", 
    "documentOf": "tender", 
    "datePublished": "2018-07-11T15:06:10.305330+03:00", 
    "documentType": "prolongationProtocol", 
    "dateModified": "2018-07-11T15:06:10.305361+03:00", 
    "id": "60bfda57b0844971a14ac7dabd950f4e"
  }
}

