POST /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/contracts/538cb657fbe54c93973e858feffa3dec/prolongations?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 179
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "decisionID": "ZM-937-99-92-2", 
    "reason": "other", 
    "documents": [], 
    "description": "Long prolongation description", 
    "datePublished": "2018-07-11T15:06:02.303227+03:00"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/contracts/538cb657fbe54c93973e858feffa3dec/prolongations
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "draft", 
    "decisionID": "ZM-937-99-92-2", 
    "description": "Long prolongation description", 
    "dateCreated": "2018-07-11T15:06:01.969656+03:00", 
    "reason": "other", 
    "datePublished": "2018-07-11T15:06:02.303227+03:00", 
    "id": "eb7e1d4d47c041c0882cd91c00952c65"
  }
}

