POST /api/2.3/auctions/bce8169f013c4b2d81b3b37b23a97c7d/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1004
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 469, 
      "valueAddedTaxIncluded": true
    }, 
    "eligible": true
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/bce8169f013c4b2d81b3b37b23a97c7d/bids/3db64c872d3343d6ae0b999fdac2de08

{
  "access": {
    "token": "bf8d4914b5ae48e2afe65d0ae4827b4f"
  }, 
  "data": {
    "status": "active", 
    "eligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-13T20:30:21.087458+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "3db64c872d3343d6ae0b999fdac2de08"
  }
}

