POST /api/2.3/auctions/e8b7de8b343844e0bb0b5d9e61256e1a/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1004
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 469, 
      "valueAddedTaxIncluded": true
    }, 
    "eligible": true
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/e8b7de8b343844e0bb0b5d9e61256e1a/bids/9eddbbd430c949f7a4cb67c0cf591b25

{
  "access": {
    "token": "2ae9b0571c8948a4a16052cf5ec2303e"
  }, 
  "data": {
    "status": "active", 
    "eligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-12-21T19:57:56.734012+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "9eddbbd430c949f7a4cb67c0cf591b25"
  }
}

