POST /api/2.5/auctions/1bd0478dee5b4b0581e2d1bf7f47fa51/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1004
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 479, 
      "valueAddedTaxIncluded": true
    }, 
    "eligible": true
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/1bd0478dee5b4b0581e2d1bf7f47fa51/bids/d9bb731980a14b76872e07b506803203
X-Content-Type-Options: nosniff

{
  "access": {
    "token": "b657058be68c4b73871152fef26a96ed"
  }, 
  "data": {
    "status": "active", 
    "eligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-07-11T15:06:07.011228+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "d9bb731980a14b76872e07b506803203"
  }
}

