POST /api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1004
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 479, 
      "valueAddedTaxIncluded": true
    }, 
    "eligible": true
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/bids/04157f8fe37c41ef94bf68990de2cfd4

{
  "access": {
    "token": "0d261c45b66345679b30319e0490bcf2"
  }, 
  "data": {
    "status": "active", 
    "eligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-01-31T17:28:43.883584+02:00", 
    "qualified": true, 
    "tenderers": [
      {
        "additionalIdentifiers": [
          {
            "scheme": "UA-FIN", 
            "id": "А01 457213"
          }
        ], 
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "04157f8fe37c41ef94bf68990de2cfd4"
  }
}

