PATCH /api/2.3/auctions/6e079f8f88084a369a554d33fa85f1f8?acc_token=264068a60d054bac86873d67542d7f66 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2016-09-09-000001", 
    "auctionPeriod": {
      "shouldStartAfter": "2016-09-24T00:00:00+03:00"
    }, 
    "tenderPeriod": {
      "startDate": "2016-09-09T19:44:50.278132+03:00", 
      "endDate": "2016-09-23T19:44:37.354534+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земля", 
          "id": "70122000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-09-11T19:44:37.354534+03:00", 
          "endDate": "2016-09-14T19:44:37.354534+03:00"
        }, 
        "id": "963e62588b2f43e4827f6d9885d05e29", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-09-09T19:44:50.278190+03:00", 
    "dateModified": "2016-09-09T19:44:50.281498+03:00", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2016-09-09T19:44:50.278132+03:00", 
      "endDate": "2016-09-23T19:44:37.354534+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2016-09-23T19:44:37.354534+03:00", 
    "id": "6e079f8f88084a369a554d33fa85f1f8", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

