PUT /api/2.3/auctions/0d788da874814db38bc3f67ef6f57a8b/documents/420a287b16924acb84cf33e8262c58a2?acc_token=3fb0279810984ff7b463b5ef6c07f04f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 338
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d77a753ef33d4fa8b6c098edbe2adc1d?KeyID=87c9f4bd&Signature=FUaZn9nWHXi0n%2BX69amMrHqAqUk7w0O%2FbH69rbzXDS5rWIGvqAtqFA8pAmFYSUjM3gRdsQZDpY1E30ULGlUJDQ%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d77a753ef33d4fa8b6c098edbe2adc1d?KeyID=87c9f4bd&Signature=NLma2M12tZJqHNhcpu7K%252BZPl9jKlWqpA3OJdQvsp7Hjb74LSs4sk3zyXdONWkK2rHRUcrzOvNstasjQKkUeOCQ%253D%253D", 
    "title": "AwardCriteria-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-20T17:01:07.562057+03:00", 
    "dateModified": "2016-09-20T17:01:07.634327+03:00", 
    "id": "420a287b16924acb84cf33e8262c58a2"
  }
}

