PUT /api/2.3/auctions/435c47dfcd164eb9806932cc6aec4056/documents/89f5f87cc3cb485298bba05aa7d80c95?acc_token=977614b74e04409bbb1213e370cef636 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 342
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e29ad8f5ce8c4c2f818cdb9ee69263d2?KeyID=85c206d4&Signature=mGZGLjWsNpkbbtnmHoultjlZzSMe%2B1sRJkHwigXglUCYN9pbuIvVDs%2BzdYmFIv15Wjgd3Yd%2FnGzB%2Fj4AlxsODg%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e29ad8f5ce8c4c2f818cdb9ee69263d2?KeyID=85c206d4&Signature=UuJq6sfk4D%252BSPmJGyJPg7EobdikHhpoF2TmWKag0BynR9ZnvkMJwNTRl2B363rsiAzPK5IDcn5pswqB1BI8cCg%253D%253D", 
    "title": "AwardCriteria-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-02T19:52:48.274998+02:00", 
    "dateModified": "2016-12-02T19:52:48.333345+02:00", 
    "id": "89f5f87cc3cb485298bba05aa7d80c95"
  }
}

