PUT /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/documents/cf91c283f3b04cb5a76d9368d69c161f?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 342
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1a8b26fa32cb42f3a69ba72c28d5db51?KeyID=172d32c8&Signature=8eDrypjKBIx1ehurKjEe%2B1ww%2FONYm2AC1P1%2BDdaEeaBUKtK9TlcGlD059rgFQvW3GYOLIcz4n%2Bx6zDaEdHO1Bg%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1a8b26fa32cb42f3a69ba72c28d5db51?KeyID=172d32c8&Signature=y9meT2iCjfA5YdUhT1lSEZ1%252BIFYd6mMcv5sauCMDJCQAoifkdIUo4zgmMqZ%2FzGbJJlixeUdA5n5%252BFhLTkfDOCQ%253D%253D", 
    "title": "AwardCriteria-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-11T15:06:07.703749+03:00", 
    "dateModified": "2018-07-11T15:06:07.765929+03:00", 
    "id": "cf91c283f3b04cb5a76d9368d69c161f"
  }
}

