PUT /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/cancellations/8d13337163de4a51b8caad7efab95a9c/documents/dd88f21f3fe049d1a769423cecefb3d2?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 329
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a07fc742725b4d368494f4e2acd5c446?KeyID=172d32c8&Signature=tZ1R7cquRGVWzK8FixEZdZ882pPynH5tcuPMNBOCfHcwnXY8WcsxnQiwIdH%2BassrCOekTqalUVZXHEPeiY46CQ%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a07fc742725b4d368494f4e2acd5c446?KeyID=172d32c8&Signature=w2R5JkOzRaWcwNBhCcnzZyBWCq23J09QvRckHrhhbtYNKhjVXgIHnfc%252BTPeo0fROyF2XEYxEgLk5SpdUWRKTBA%253D%253D", 
    "title": "Notice-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-11T15:06:11.358918+03:00", 
    "dateModified": "2018-07-11T15:06:11.640471+03:00", 
    "id": "dd88f21f3fe049d1a769423cecefb3d2"
  }
}

