PUT /api/2.3/auctions/56c507ca68744c5f964933955043072a/cancellations/769c51f88c934e6eadc6085428a997ee/documents/bee06398225f48f58539f70d1a8f5500?acc_token=2ac7aaf0d5b2429e9024f281f75c0eaf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 331
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a9dbb50f3a0a46bd87c4270c790a5f0c?KeyID=8f3407b6&Signature=CJ%2BPLq8EkgPAuxA6YTrBUY3xTxJbgNZlZ3ETba0LKhnIIWLZ%2FG78xnBj1J2tXACieajOgZL669aIJI5m2sHVCg%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a9dbb50f3a0a46bd87c4270c790a5f0c?KeyID=8f3407b6&Signature=AblWlPtdKmPP1t%2FwUcD9jUhtJz1aH97CcQEY5nccpPS1XP8RyN3Iz%2FzqLl56pRTcwXHI5SZxF1BxvExnJibGDQ%253D%253D", 
    "title": "Notice-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-01T13:22:24.723823+02:00", 
    "dateModified": "2017-02-01T13:22:25.042479+02:00", 
    "id": "bee06398225f48f58539f70d1a8f5500"
  }
}

