POST /api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/documents?acc_token=aca8b1f9f9574f34a0942083cb65db8b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 428
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "title": "first_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bef91a5aaa0b4d1fb05bf744ebf8820c?KeyID=e10a37aa&Signature=hICg2ooW1mJiUEyC5Lx71IMFlPXJpLHofRVrxVtQD2R2T5Lm4h4u06jaRwRzlZ8l57fXktcGZxKZS8YDQ%2Fc0AA%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/documents/d6e7847e17734a6a866405b3244ceef3

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bef91a5aaa0b4d1fb05bf744ebf8820c?KeyID=e10a37aa&Signature=aoWUj0ZPSJhNL3j9CoZffcR5mK9L108calUf2jCpNvQmuqtN6sUeIctG3Y6a75TF9pBjyhUtJ5qRJ%2FKBylEBDA%253D%253D", 
    "title": "first_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-02-13T20:30:23.119916+02:00", 
    "documentType": "illustration", 
    "id": "d6e7847e17734a6a866405b3244ceef3", 
    "dateModified": "2017-02-13T20:30:23.119950+02:00"
  }
}

