POST /api/2.3/auctions/f67956e32a634f98a9ab9ad7c2b84e02/documents?acc_token=5d03fcac4be247fdb9b9db02ff5dd4e4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 436
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "title": "third_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c4b484b4e7564033be8bcd52576dc9ab?KeyID=7a220e8f&Signature=q%2Fb5IYQSHEzSoW3L4C5yU7mbiJ2OSyWoY2msG%2BTDJ3b6meff92YRSFaZGtvf%2FbrI017TfzZt%2FtzpLYe%2FWepOBQ%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/f67956e32a634f98a9ab9ad7c2b84e02/documents/dcf1796f235e4e00ba3428c878527136

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c4b484b4e7564033be8bcd52576dc9ab?KeyID=7a220e8f&Signature=2X7vQ8Tg6nJ%2FM0foIL6aIv0xcKhqd2MzjhUj33wbrq5PwWHKbmTsUmIeGBYVNaYkHBDSMzz%252BibfRU4jy%2F8i8Bw%253D%253D", 
    "title": "third_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2016-12-21T19:57:58.584576+02:00", 
    "documentType": "illustration", 
    "dateModified": "2016-12-21T19:57:58.584604+02:00", 
    "id": "dcf1796f235e4e00ba3428c878527136"
  }
}

