POST /api/2.3/auctions/2077a4e50e744ab6bc3936e6a0bb77a0/bids/d1c66a2ce84d4feaab56c312b13ead4d/documents?acc_token=fcd6d3da53ec4cddae13d6cbc2dddb3c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 329
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f57c9558d6c24cfda2056cae116abeba?KeyID=c414de0e&Signature=NIOvIpEUXUk0Hw7AUJSbrjnH4aUfYsBzQNZCqEwA8g%2FrpLO5HbFHCy29tPmXecN2oz5UOeuNO3vguDUoUWvOBg%3D%3D", 
    "title": "Proposal.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2077a4e50e744ab6bc3936e6a0bb77a0/bids/d1c66a2ce84d4feaab56c312b13ead4d/documents/b3fbb2121f884df0a7ba7ffe55006f10

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/2077a4e50e744ab6bc3936e6a0bb77a0/bids/d1c66a2ce84d4feaab56c312b13ead4d/documents/b3fbb2121f884df0a7ba7ffe55006f10?download=f57c9558d6c24cfda2056cae116abeba", 
    "title": "Proposal.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-11-25T12:16:19.600711+02:00", 
    "dateModified": "2016-11-25T12:16:19.600736+02:00", 
    "id": "b3fbb2121f884df0a7ba7ffe55006f10"
  }
}

