POST /api/2.3/auctions/06a31c1ae5d048d0ad5723f2c81f2495/documents?acc_token=1e38e432232d499aadedfa06b7d96bae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 154
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "Asset_Familiarization.pdf", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentType": "x_dgfAssetFamiliarization"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/06a31c1ae5d048d0ad5723f2c81f2495/documents/2bcdc11607cf4c96a0bc617410ff866f

{
  "data": {
    "title": "Asset_Familiarization.pdf", 
    "format": "offline/on-site-examination", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentOf": "tender", 
    "datePublished": "2016-12-02T18:19:09.742143+02:00", 
    "documentType": "x_dgfAssetFamiliarization", 
    "dateModified": "2016-12-02T18:19:09.742191+02:00", 
    "id": "2bcdc11607cf4c96a0bc617410ff866f"
  }
}

