POST /api/2.3/auctions/bbc1fa45fd914ed9911f8a5daf54e7d9/bids/026bb5de1cda4654b6f1d84aba2097e4/documents?acc_token=a6502a0d20da47e0aa164e802b2fe7dc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 381
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/38ba2ad544c747d0b6ae02ac41fc54f6?KeyID=79022feb&Signature=S148lPndbesbRfcCXK%2BxKCa9knEt3PDbSz4keWt3mo0W%2FuWK%2FJwQ2JfrDuxanDOGD0hjw43%2BDYo%2BaN1lu3DVDw%3D%3D", 
    "title": "FinancialLicense.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "financialLicense"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/bbc1fa45fd914ed9911f8a5daf54e7d9/bids/026bb5de1cda4654b6f1d84aba2097e4/documents/6b7160f1e77f41eda78b76155e3de0b9

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/bbc1fa45fd914ed9911f8a5daf54e7d9/bids/026bb5de1cda4654b6f1d84aba2097e4/documents/6b7160f1e77f41eda78b76155e3de0b9?download=38ba2ad544c747d0b6ae02ac41fc54f6", 
    "title": "FinancialLicense.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-13T15:47:16.511008+02:00", 
    "documentType": "financialLicense", 
    "dateModified": "2017-02-13T15:47:16.511035+02:00", 
    "id": "6b7160f1e77f41eda78b76155e3de0b9"
  }
}

