POST /api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/documents?acc_token=0052e89467e54a799389e87c87910599 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 432
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "title": "first_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/da7171338cfd40daaf0a363d1da7be8c?KeyID=172d32c8&Signature=44NDlwGUSjchl%2F1E9rd8cJIkXYeL%2FbHuVYTGAW8qTMiKBcATXGrfJC3TFdBElOlF%2FLmzbRZmQOGj3UmUjE7dBg%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.5/auctions/bb1795e42a4243ada1433ddb18b4f06f/documents/dbe0ca0c582b422d84c59a2aa93eb948
X-Content-Type-Options: nosniff

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/da7171338cfd40daaf0a363d1da7be8c?KeyID=172d32c8&Signature=UPMVnKZTzNNA9AxDywJSZbpPjStBGoee80QWYvawEzzQnVYTxYuijJO8UMScqwMcbt5qrdjYn5jyfUyhvZzkDA%253D%253D", 
    "title": "first_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2018-07-11T15:06:07.828825+03:00", 
    "documentType": "illustration", 
    "dateModified": "2018-07-11T15:06:07.828844+03:00", 
    "id": "dbe0ca0c582b422d84c59a2aa93eb948"
  }
}

