POST /api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/documents?acc_token=aca8b1f9f9574f34a0942083cb65db8b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 338
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/220b1dc16d2b4d9599e75c539e4ca132?KeyID=e10a37aa&Signature=VqESdUD0q16V9qQ%2B39JAeWi49ipZcW%2FTNuqdM5g4rr0EK20zsfHLFWeSiZ5Y5vJBMS%2FBueU1WaWaoaS1zkC1CA%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/c4dd4d72218b43df8603bf9ceffd09d9/documents/de4e050392ac4a5e85d44cd9d6d17d83

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/220b1dc16d2b4d9599e75c539e4ca132?KeyID=e10a37aa&Signature=SDQCM6eJpNhQtgZr95KKXWxG8RShyTlJqJqG1iAhlr1Qk%252BfB%2FfXDgxVWy4yVHMXMCszAfd5LvSlhP9cUTXMvDg%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-13T20:30:22.987435+02:00", 
    "dateModified": "2017-02-13T20:30:22.987468+02:00", 
    "id": "de4e050392ac4a5e85d44cd9d6d17d83"
  }
}

