POST /api/2.3/auctions/56c507ca68744c5f964933955043072a/documents?acc_token=2ac7aaf0d5b2429e9024f281f75c0eaf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 430
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "title": "first_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/706d73b92a65446199d1d0573963d601?KeyID=8f3407b6&Signature=KjHBSwz4JyFIRkvYmubAy0GZI2SHGsP1OtuXs56fmgnxov1RMk6Fxtj0LQzl1VpF8lg%2BzN5N%2FW8ypFmnr4QwDg%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/56c507ca68744c5f964933955043072a/documents/e7803c183b6e4ec9a45529d5b5896b21

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/706d73b92a65446199d1d0573963d601?KeyID=8f3407b6&Signature=AUG0Ux1M3qgW8e1mtYzVaHy55h1MSBWrP9V%2Fy9SbMmwnzRYTSU3f0FP%2FuW%2FmGCpZhDj4zfyx6Dh6bfp8ByQcAw%253D%253D", 
    "title": "first_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-02-01T13:22:21.233533+02:00", 
    "documentType": "illustration", 
    "dateModified": "2017-02-01T13:22:21.233582+02:00", 
    "id": "e7803c183b6e4ec9a45529d5b5896b21"
  }
}

