POST /api/2.3/auctions/0d788da874814db38bc3f67ef6f57a8b/documents?acc_token=3fb0279810984ff7b463b5ef6c07f04f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 338
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/de8f00f34a1443318ad251c282505305?KeyID=87c9f4bd&Signature=AocrvHFcrtZVdsjY%2FXv7KzZ5lmeBBrAj01rMT9Okovk%2BFtBWFvICUSjqTkJa4tTMDgLSPDWv51%2BHkd7Pddb6AQ%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0d788da874814db38bc3f67ef6f57a8b/documents/420a287b16924acb84cf33e8262c58a2

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/de8f00f34a1443318ad251c282505305?KeyID=87c9f4bd&Signature=WUyf3SruYL6dm6a%2FnaziYTPpt84aQ9NfwVJ2LHGOOu80fjPELDlXkEp9heMGnLyPJH0R8nqtTXTuAex2owE0Bg%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-20T17:01:07.562057+03:00", 
    "dateModified": "2016-09-20T17:01:07.562089+03:00", 
    "id": "420a287b16924acb84cf33e8262c58a2"
  }
}

