POST /api/2.3/auctions/eeca007469eb4a9a8b9cd75d32289e6f/documents?acc_token=6b7f670ea82344f7b86f417766d3025c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 418
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "title": "third_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/102b7857da984967817921a223f987ac?KeyID=1d13b7f9&Signature=vMVrnU8SLc1vTFrH8srkwWV3Xq8n%2BAj05LsYZiuQNbbmwzW%2FIrZGfHLwTOEFWEz3GkVuf7qZAP2boaOsxIT0Dw%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/eeca007469eb4a9a8b9cd75d32289e6f/documents/c9961b8a08f04f8399f590a67224a02e

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/102b7857da984967817921a223f987ac?KeyID=1d13b7f9&Signature=P7ju1te%2F3INWZ9h7OBBoZFyinCK6SXETXK1s0htgrt9CJ4fl8BZkxHmfsraJrBUFjdtM4n3i%2F1FuzNo5TXz8Dg%253D%253D", 
    "title": "third_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2016-09-19T15:13:52.468181+03:00", 
    "documentType": "illustration", 
    "id": "c9961b8a08f04f8399f590a67224a02e", 
    "dateModified": "2016-09-19T15:13:52.468223+03:00"
  }
}

