POST /api/2.3/auctions/bfddd8a61d1d49d19156b1e40ccb6e82/documents?acc_token=43aa4293fcda49779bcb3fdb208d87fe HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 424
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/addf407fa9a6497bac75e478acc0dcff?KeyID=dc8e6bab&Signature=WJtZ%2F9ftOL9k1PLqVcgSO%2BFuEyd%2FzpuVvhY4iuP%2Br11mTFx7C5adOhrjqnreD%2BTd4kSroU%2BXCPciM%2Bmz7jx0AQ%3D%3D", 
    "format": "application/pdf", 
    "documentType": "technicalSpecifications"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/bfddd8a61d1d49d19156b1e40ccb6e82/documents/b0d33b7113c3412f95ef09ee1adb282a

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/addf407fa9a6497bac75e478acc0dcff?KeyID=dc8e6bab&Signature=VOw9t%252BSzdCWm2EG9PiiP4lvP5ogpZ2ioRzKemW4xV0uhFMFAozrW86f2TaQ7AZIZi6BbF928mM1UNidTBXzqCA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-02T19:52:46.213715+02:00", 
    "documentType": "technicalSpecifications", 
    "dateModified": "2016-12-02T19:52:46.213743+02:00", 
    "id": "b0d33b7113c3412f95ef09ee1adb282a"
  }
}

