POST /api/2.3/auctions/4f130ddaab1f46e69ac45a15dff6a04d/documents?acc_token=97871eeba234475291b2a6905fa607c6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 436
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d5601d38dd4243baad7cad4d5b9a877a?KeyID=54b15984&Signature=NfkJne%2BYKkyIbxecoE%2Bkt6nMcie%2BmAi3lJhj6FqOugFbzkUJYOYPVhU%2FcNbJqb5MXgPPDISLdMBrI3XcFTXbCQ%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/4f130ddaab1f46e69ac45a15dff6a04d/documents/9cac5d4d8cb148bfa2c847ac01cc262f

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d5601d38dd4243baad7cad4d5b9a877a?KeyID=54b15984&Signature=W0EW0aYfKHFMvHh1a%2Ff3CPLRZVNXmsQtj%2FloWp28%2FEVa7Jk08cM4K%252BC8MbwHctRhOOdSM7%252BiagZkO3IzMm42Aw%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2016-11-29T12:46:32.989810+02:00", 
    "documentType": "illustration", 
    "id": "9cac5d4d8cb148bfa2c847ac01cc262f", 
    "dateModified": "2016-11-29T12:46:32.989838+02:00"
  }
}

