POST /api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/documents?acc_token=bc559bc7190d4ed5bedd0894c8229f50 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 418
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/41ae46967b604005a9fae58c861c3afc?KeyID=b1d2ffa5&Signature=4IXugAkcxOuJfKdFRMMJ%2BQ%2B0j0242LAgnqgQ1tdxGfvZ8r%2Bp3KCMC7AiWamxfKosI%2BS0rKwFArD55uhhZSuUBA%3D%3D", 
    "format": "application/pdf", 
    "documentType": "technicalSpecifications"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/documents/a3890eebdcf54260b86ff54468bde198

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/41ae46967b604005a9fae58c861c3afc?KeyID=b1d2ffa5&Signature=hQreQoMXvDdNLDW4l5YnsqYZ9Kgbh5r75tS001m3FZCCFdkWnL1RRxnHALIGt2TGYEnyvq7rvblYyZCRxsR2Dw%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-01-31T17:28:43.338501+02:00", 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-01-31T17:28:43.338530+02:00", 
    "id": "a3890eebdcf54260b86ff54468bde198"
  }
}

