POST /api/2.3/auctions/f6a8d0f1fd564397b3f1fd30ce85b004/documents?acc_token=b71ba50d2bc1415db843b262774e02e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 436
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1912057e75324bb28bcee5e7874487e0?KeyID=91671178&Signature=5aDhy9%2F1Ca5vpYQLEMjaMdGeuAR%2Fh5lRBAdhgC8SrmS4vVD9p%2FwJPvs%2FyjuB9Xi97rtOhWGo1bporD5NA2DhDg%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/f6a8d0f1fd564397b3f1fd30ce85b004/documents/12163c496da04e6bb8b182908b509306

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1912057e75324bb28bcee5e7874487e0?KeyID=91671178&Signature=xtJhuAQL93fR4cIsPp6Swa8Z0SU65II5bWyKrlQKtXQgpR%2F6bncpeIakyk1ZAkrsG8mUMNsBJVyQwwW9lwHCCQ%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-02-15T11:48:44.603123+02:00", 
    "documentType": "illustration", 
    "dateModified": "2017-02-15T11:48:44.603151+02:00", 
    "id": "12163c496da04e6bb8b182908b509306"
  }
}

