POST /api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/documents?acc_token=2b1b3d8fd6be4827908b19fdf46323d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 432
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/173103c9c3bc4a25b2b6bacc9e865e2c?KeyID=e578eecc&Signature=X7qHlXnvUX7xYMaCXKhZTZoiExxclc5L6au70hd6tdMdWwrUs6lWJ8%2FLpH%2BJw0turFVn9tUhB1euDnDA98GeAQ%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/0bbf22e936f24d158f6d695b84b2de2f/documents/4de8c3f245db45bdb378b07749fd28c2

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/173103c9c3bc4a25b2b6bacc9e865e2c?KeyID=e578eecc&Signature=9%2Fe6BkwhMDS6bF4XIQhRDfuPoRXpKbJIFWixjkltzsi75o3G7CgvVUfcvM7K9G3xMwUSaUC5AbNqs35ZF68OCA%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2018-03-13T14:17:03.739578+02:00", 
    "documentType": "illustration", 
    "dateModified": "2018-03-13T14:17:03.739603+02:00", 
    "id": "4de8c3f245db45bdb378b07749fd28c2"
  }
}

