POST /api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/bids/295800922aeb489faecf4ea8b77ca14e/documents?acc_token=78560de92bb048cebe5502ef8c72b948 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 375
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ccf8d0c180af44fd87e8781b40eb145e?KeyID=b1d2ffa5&Signature=aEkpiPhC37Z2LhmQMv8MnPajfrmk3c8KNDRTtXotTmz0Cl581afkXsfr01wRhHY7nDLQ07%2FE%2FZHvI4BBvtcGAw%3D%3D", 
    "title": "FinancialLicense.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "financialLicense"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/bids/295800922aeb489faecf4ea8b77ca14e/documents/8feea7578e6c425e8c0746358ae1d43d

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/59c1a71d8b624340985fa04bb5bc427c/bids/295800922aeb489faecf4ea8b77ca14e/documents/8feea7578e6c425e8c0746358ae1d43d?download=ccf8d0c180af44fd87e8781b40eb145e", 
    "title": "FinancialLicense.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-01-31T17:28:43.772126+02:00", 
    "documentType": "financialLicense", 
    "dateModified": "2017-01-31T17:28:43.772157+02:00", 
    "id": "8feea7578e6c425e8c0746358ae1d43d"
  }
}

