POST /api/2.3/auctions/34a03244dd6642f2bcd612f434c6c913/documents?acc_token=5516b94f9ffc499db4da6ab04ce35f90 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 329
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d21fc57fa0a34e1a91983769b606380c?KeyID=3f83c312&Signature=QlYxkaLsjv5wddxXGVZNp2a9ikhvHf3xIHQ2khf9yV%2FgrDEt5m0dWvxvezPfJO70ierZBqfXEh8%2FAmo1VDu9CA%3D%3D", 
    "title": "Notice.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/34a03244dd6642f2bcd612f434c6c913/documents/ca25f3a06467492aa0eda82b2e1d2f25

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d21fc57fa0a34e1a91983769b606380c?KeyID=3f83c312&Signature=gs9Xw6U8miDuVlEfeRqsv%2FrDfcWkAs%2F7trhmSJi28G07j2xjHRmwYPr4m9htiC9UJcqn0g%2Fe2a%252BIuA5bBszSCA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-09-16T14:46:07.236531+03:00", 
    "dateModified": "2016-09-16T14:46:07.236569+03:00", 
    "id": "ca25f3a06467492aa0eda82b2e1d2f25"
  }
}

