PATCH /api/2.3/auctions/331e9ef3d78d46cfb3df35c17b0650c7/awards/e5ff037d8e964151b6cb1d2a00a205e2?acc_token=5303e3bebff44ed3a5a9f8f7db899743 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending.payment"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending.payment", 
    "paymentPeriod": {
      "startDate": "2017-04-07T15:31:22.815369+03:00", 
      "endDate": "2017-04-07T15:51:22.815369+03:00"
    }, 
    "documents": [
      {
        "dateModified": "2017-04-07T15:31:23.191237+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1b3254efe97a43fe8c32d50835dcf2cb?KeyID=df79319d&Signature=ZfY1BOFDOQLc%252B%252B%2FoCwOmd%2FKFmwfIpmgnkAZnau3WnH0go%2F6iFpVmsSV%252BkzWncGkpoJlBsLohaoFfOspcteXTBg%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-04-07T15:31:23.191202+03:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "6bee80d99c2e40728271fa1d6a076696"
      }, 
      {
        "dateModified": "2017-04-07T15:31:23.312959+03:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6495273a1db3420897958969af4b63b7?KeyID=df79319d&Signature=48yS5V6Lg9SXCRMDK0lEA9%2F%2FG8XQneARWvQcmVD%252BxDkxJPlT%252Bkcy6FPU0kmSvacNCc7cUx7DTZmEMy3H80LkCg%253D%253D", 
        "author": "auction_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-04-07T15:31:23.312917+03:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "70b1da92f7a04bada8aa4b04fa75c29c"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2017-04-07T15:31:22.815369+03:00", 
      "endDate": "2017-04-07T15:31:23.473116+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-04-07T15:31:22.815369+03:00", 
      "endDate": "2017-04-07T15:51:22.815369+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "signingPeriod": {
      "startDate": "2017-04-07T15:31:22.815369+03:00", 
      "endDate": "2017-04-07T15:51:22.815369+03:00"
    }, 
    "bid_id": "0743a2c22cc24b19ad9bf844fdf98e50", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-04-07T15:31:23.486630+03:00", 
    "id": "e5ff037d8e964151b6cb1d2a00a205e2"
  }
}

