PATCH /api/2.3/auctions/f6a8d0f1fd564397b3f1fd30ce85b004/awards/9bd8a6d2f7624bcebe94c2333eb5cbc7?acc_token=b71ba50d2bc1415db843b262774e02e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending.payment"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending.payment", 
    "paymentPeriod": {
      "startDate": "2017-02-15T11:48:46.210702+02:00", 
      "endDate": "2017-02-15T11:59:46.210702+02:00"
    }, 
    "documents": [
      {
        "dateModified": "2017-02-15T11:48:46.613698+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6dd84eb79863499facffb3e5652d42d5?KeyID=91671178&Signature=J6jkWeSMLS7Bd%252BeTsuXwYaIMgrnvAmJHEbxFzYDEPg6PAsB%252B4grcicD7EIGTzea3pniKw2yAv3peEnHqzmmGCQ%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-02-15T11:48:46.613661+02:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "955aa34cbd224133bb12934b22483e87"
      }, 
      {
        "dateModified": "2017-02-15T11:48:46.753442+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a3c68b255d504bf28e8a006b5fe82c59?KeyID=91671178&Signature=%252BaEaPrTjk6CEwDBMLOrUq9Y%2F9ZkOPc7jbYWmnFJVpTPQm30aDHaQFblvXv2GNmcq0K9lCwjx6ISK4h8AJs%2FTBg%253D%253D", 
        "author": "auction_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-02-15T11:48:46.753410+02:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "efa2d54da4b340ea8e39c8a15c0ef059"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2017-02-15T11:48:46.210702+02:00", 
      "endDate": "2017-02-15T11:48:46.901914+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-02-15T11:48:46.210702+02:00", 
      "endDate": "2017-02-15T11:59:46.210702+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "signingPeriod": {
      "startDate": "2017-02-15T11:48:46.210702+02:00", 
      "endDate": "2017-02-15T11:59:46.210702+02:00"
    }, 
    "bid_id": "af88ae708f384bdd9a9d2a6740759998", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-15T11:48:46.915619+02:00", 
    "id": "9bd8a6d2f7624bcebe94c2333eb5cbc7"
  }
}

