PATCH /api/2.3/auctions/007f509a6dbd4f67b07d33bcad157bd5/awards/5da46ef46a5c4af6b4b11086df9eb89c?acc_token=293b1515fb11485080bdb821d1cb3420 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending.payment"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending.payment", 
    "paymentPeriod": {
      "startDate": "2017-02-13T15:47:19.855768+02:00", 
      "endDate": "2017-02-13T15:58:19.855768+02:00"
    }, 
    "documents": [
      {
        "dateModified": "2017-02-13T15:47:19.616351+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/05a2c7e16645433cb4c99516152e085f?KeyID=58a82d14&Signature=WG9U8ofRXH6onAQjHQtJ9C2TSWuPUaE1eQPmMuc80686jQVpCr7Bq9TPHB%252BxgpixS1J9NupgUHuzVvEdz3eeBw%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-02-13T15:47:19.616321+02:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "971f3ed86d8b435795b096ec5f680d55"
      }, 
      {
        "dateModified": "2017-02-13T15:47:19.721651+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7ca175ce77834450a755eb1a79183667?KeyID=58a82d14&Signature=wGiZZNcRpPOmr9TyHJJIPeh8z6FdmMzAoIhODyPzGKLhWzpFcp9XizIUeinraC3%2FB%252BBScO4hdSNd93krIviDDg%253D%253D", 
        "author": "auction_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-02-13T15:47:19.721624+02:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "e46dab5e500a4b9599cf82cad1f77987"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2017-02-13T15:47:19.290873+02:00", 
      "endDate": "2017-02-13T15:47:19.855768+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-02-13T15:47:19.290873+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "signingPeriod": {
      "startDate": "2017-02-13T15:47:19.855768+02:00", 
      "endDate": "2017-02-13T15:58:19.855768+02:00"
    }, 
    "bid_id": "69e66e230eb844e193200a934d842aeb", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-13T15:47:19.867860+02:00", 
    "id": "5da46ef46a5c4af6b4b11086df9eb89c"
  }
}

